// Auto-generated by scripts/generate-data.mjs
// Do not edit this file directly.
export const APP_BUILD_META = {
  "frontend_version": "2.0.138",
  "backend_version": "2.0.138",
  "data_version": "data.138.6a81aa1",
  "generated_at": "2026-07-08T06:35:06.480Z",
  "source_summary": "source=server/handlers/efficiency-data.json; sha256=3e2d9d00f5d2; workplaces=14; trading_rule_groups=7; manufacturing_rule_groups=9; control_center_rules=22",
  "git_sha": "6a81aa196278148414a306027a90241f966805ba",
  "build_context": "push"
} as const;

export type AppBuildMeta = typeof APP_BUILD_META;
