// Auto-generated by scripts/generate-data.mjs
// Do not edit this file directly.
export const APP_BUILD_META = {
  "frontend_version": "1.3.108",
  "backend_version": "1.3.108",
  "data_version": "data.108.2b499e8",
  "generated_at": "2026-07-01T16:02:44.740Z",
  "source_summary": "source=netlify/functions/efficiency-data.json; sha256=adfae57833a7; workplaces=14; trading_rule_groups=7; manufacturing_rule_groups=9; control_center_rules=13",
  "git_sha": "2b499e81a07336f05be7b6bd1c8afde0aeb7a3cb",
  "build_context": "local"
} as const;

export type AppBuildMeta = typeof APP_BUILD_META;
