// Auto-generated by scripts/generate-data.mjs
// Do not edit this file directly.
export const APP_BUILD_META = {
  "frontend_version": "2.0.114",
  "backend_version": "2.0.114",
  "data_version": "data.114.4e0a429",
  "generated_at": "2026-07-07T09:44:51.148Z",
  "source_summary": "source=server/handlers/efficiency-data.json; sha256=e432f4cae89e; workplaces=14; trading_rule_groups=7; manufacturing_rule_groups=9; control_center_rules=13",
  "git_sha": "4e0a429be6b8355d4556d718617e557c9f8ccb70",
  "build_context": "push"
} as const;

export type AppBuildMeta = typeof APP_BUILD_META;
