export const adminCopy = {
  registration_nav: '注册设置',
  registration_loading: '正在载入注册设置...',
  registration_load_failed: '加载注册设置失败',
  registration_save_failed: '保存注册设置失败',
  registration_saved: '注册设置已保存；新配置只影响之后创建的账号。',
  registration_eyebrow: '账号安全',
  registration_title: '新用户注册',
  registration_description: '控制新账号的邮箱验证与邀请准入要求。',
  registration_toggle: '注册时要求验证邮箱',
  registration_invite_toggle: '仅邀请可注册',
  registration_enabled_help: '开启邮箱验证后，新用户注册完成前不会获得登录会话；验证成功后将自动登录。',
  registration_disabled_help: '关闭邮箱验证后，新用户会恢复为注册即登录。已有未验证账号不会被自动激活。',
  registration_invite_help: '开启仅邀请注册后，新用户必须提交有效的管理员邀请码；普通用户推荐码不能满足准入要求。关闭后，两类邀请码均恢复为可选。',
  registration_save: '保存注册设置',
  registration_saving: '保存中...',
  registration_reload: '重新载入',
  registration_updated: '最近更新：',
  registration_default: '使用默认配置',
  registration_brevo_eyebrow: '邮件配额',
  registration_brevo_title: '今日 Brevo 邮件',
  registration_brevo_description: '统计本系统通过 Brevo 发送的邮件，并按 UTC 00:00 重置每日 300 封额度。',
  registration_brevo_used: '有效占用：',
  registration_brevo_remaining: '有效剩余：',
  registration_brevo_reached: '今日额度已用尽',
  registration_brevo_available: '额度可用',
  registration_brevo_date: '日期',
  registration_brevo_sent: '已发送',
  registration_brevo_verification: '邮箱验证',
  registration_brevo_admin_invite_verification: '管理员邀请验证',
  registration_brevo_reset: '密码重置',
  registration_brevo_cancel: '注销取消',
  registration_brevo_receipt: '注销回执',
  registration_brevo_failed: '失败',
  registration_brevo_timezone: '统计时区：',
  registration_brevo_pending: '处理中或结果待确认：',
  registration_brevo_official_title: 'Brevo 官方额度',
  registration_brevo_official_remaining: '官方剩余额度',
  registration_brevo_official_used: '官方已使用',
  registration_brevo_local_used: '本地账本占用',
  registration_brevo_external_offset: '外部消耗偏移',
  registration_brevo_unknown: '—',
  registration_brevo_sync_status: '官方同步状态：',
  registration_brevo_synced_at: '最近成功同步：',
  registration_brevo_never_synced: '尚未成功同步',
  registration_brevo_sync_fresh: '已同步',
  registration_brevo_sync_stale: '同步失败，使用旧快照',
  registration_brevo_sync_unavailable: '暂不可用，使用本地账本',
  registration_quota_action_title: '额度用尽时的新用户注册策略',
  registration_quota_pause: '暂停注册',
  registration_quota_pause_help: '达到 300 封后拒绝新的注册请求，并提示用户明日再试。',
  registration_quota_allow: '允许免验证注册',
  registration_quota_allow_help: '仅在额度用尽时跳过验证邮件，并将新账号直接标记为邮箱已验证。',
  registration_quota_warning: '安全提示：额度用尽期间将无法确认新用户是否拥有所填写的邮箱地址。',
  registration_reserve_title: '分级邮件预留',
  registration_admin_invite_reserve: '管理员邀请验证预留',
  registration_password_reset_reserve: '密码重置预留',
  registration_reserve_help: '普通邮件会同时保留两类额度；管理员邀请验证只保留密码重置额度；密码重置可使用全部剩余额度。',
  registration_reserve_total_error: '两类邮件预留总和不能超过 300。',
  registration_reserve_range_error: '每项邮件预留必须是 0 到 300 之间的整数。',
  registration_capacity_standard: '普通邮件可用',
  registration_capacity_admin_invite: '管理员邀请可用',
  registration_capacity_password_reset: '密码重置可用',
  registration_admin_invites_eyebrow: '受控准入',
  registration_admin_invites_title: '管理员一次性邀请码',
  registration_admin_invites_description: '邀请码固定 7 天有效、只能使用一次且不绑定邮箱。系统不会发送邀请邮件。',
  registration_admin_invites_create: '生成邀请码',
  registration_admin_invites_creating: '生成中...',
  registration_admin_invites_once: '明文邀请码只显示这一次。请立即复制注册链接；丢失后只能撤销并重新生成。',
  registration_admin_invites_code: '邀请码',
  registration_admin_invites_link: '注册链接',
  registration_admin_invites_copy: '复制链接',
  registration_admin_invites_copied: '注册链接已复制。',
  registration_admin_invites_load_failed: '加载管理员邀请码失败',
  registration_admin_invites_create_failed: '生成管理员邀请码失败',
  registration_admin_invites_revoke_failed: '撤销管理员邀请码失败',
  registration_admin_invites_empty: '当前筛选下没有管理员邀请码。',
} as const
