export const authCopy = {
  // src/components/AuthForm.tsx
  components_AuthForm_001: "发送重置邮件失败，请稍后重试",
  // src/components/AuthForm.tsx
  components_AuthForm_002: "如果该邮箱已注册，重置密码邮件已发送，请检查收件箱。",
  // src/components/AuthForm.tsx
  components_AuthForm_003: "登录失败",
  // src/components/AuthForm.tsx
  components_AuthForm_004: "注册失败",
  // src/components/AuthForm.tsx
  components_AuthForm_005: "登录失败",
  // src/components/AuthForm.tsx
  components_AuthForm_006: "注册失败",
  // src/components/AuthForm.tsx
  components_AuthForm_007: "登录方式",
  // src/components/AuthForm.tsx
  components_AuthForm_008: "登录",
  // src/components/AuthForm.tsx
  components_AuthForm_009: "注册",
  // src/components/AuthForm.tsx
  components_AuthForm_010: "重置密码",
  // src/components/AuthForm.tsx
  components_AuthForm_011: "邮箱",
  // src/components/AuthForm.tsx
  components_AuthForm_012: "密码",
  // src/components/AuthForm.tsx
  components_AuthForm_013: "CDK（可选）",
  // src/components/AuthForm.tsx
  components_AuthForm_014: "稍后在账号页兑换",
  // src/components/AuthForm.tsx
  components_AuthForm_015: "邀请码（可选）",
  // src/components/AuthForm.tsx
  components_AuthForm_016: "10 位邀请码",
  // src/components/AuthForm.tsx
  components_AuthForm_017: "忘记密码？",
  // src/components/AuthForm.tsx
  components_AuthForm_018: "返回登录",
  // src/components/AuthForm.tsx
  components_AuthForm_019: "处理中...",
  // src/components/AuthForm.tsx
  components_AuthForm_020: "登录",
  // src/components/AuthForm.tsx
  components_AuthForm_021: "创建账号",
  // src/components/AuthForm.tsx
  components_AuthForm_022: "发送重置邮件",
  // src/components/AuthForm.tsx
  components_AuthForm_023: "请输入邮箱",
  // src/components/AuthForm.tsx
  components_AuthForm_024: "请输入正确的邮箱地址",
  // src/components/AuthForm.tsx
  components_AuthForm_025: "请输入密码",
  // src/components/AuthForm.tsx
  components_AuthForm_026: "密码至少需要 8 位",
  // src/components/AuthForm.tsx
  components_AuthForm_027: "请输入有效的 10 位邀请码",
  // src/components/AuthForm.tsx
  components_AuthForm_028: "验证邮件已发送，请检查收件箱并点击链接完成注册。",
  // src/components/AuthForm.tsx
  components_AuthForm_029: "重新发送验证邮件失败，请稍后重试",
  // src/components/AuthForm.tsx
  components_AuthForm_030: "如果该账号仍需验证，验证邮件已发送，请检查收件箱。",
  // src/components/AuthForm.tsx
  components_AuthForm_031: "重新发送验证邮件",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_001: "验证链接无效或已过期。",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_002: "正在验证邮箱...",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_003: "邮箱验证成功，正在进入工作台。",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_004: "账号安全",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_005: "验证邮箱",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_006: "完成验证后将自动登录，并进入你的账号工作台。",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_007: "重试验证",
  // src/pages/VerifyEmailPage.tsx
  pages_VerifyEmailPage_008: "返回登录并重新发送邮件",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_001: "撤销链接无效或已过期。",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_002: "注销请求已撤销。你现在可以正常登录。",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_003: "账号安全",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_004: "撤销账号注销",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_005: "确认后将恢复账号及现有工作台数据；此操作不会重新生成或修改任何排班方案。",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_006: "正在处理...",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_007: "撤销注销",
  // src/pages/CancelAccountDeletionPage.tsx
  pages_CancelAccountDeletionPage_008: "返回登录",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_001: "重置链接无效或已过期。",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_002: "请确认新密码",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_003: "两次输入的密码不一致",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_004: "重置密码失败",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_005: "密码已重置，请使用新密码登录。",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_006: "账号安全",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_007: "重置密码",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_008: "设置新密码后可返回工作台继续管理账号和排班数据。",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_009: "新密码",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_010: "确认新密码",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_011: "重置中...",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_012: "重置密码",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_013: "返回登录",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_014: "请输入密码",
  // src/pages/ResetPasswordPage.tsx
  pages_ResetPasswordPage_015: "密码至少需要 8 位",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_001: "账号入口",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_002: "MAA 基建排班工作台",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_003: "准备数据，生成下一份排班。",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_004: "登录后添加游戏账号，确认森空岛或 MAA 数据来源，再按当前干员池生成可导入的基建排班 JSON。",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_005: "数据确认",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_006: "昵称与 UID",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_007: "安全边界",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_008: "无需密码",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_009: "最终结果",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_010: "账号登录与注册",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_011: "继续到工作台",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_012: "登录或创建账号",
  // src/pages/tool/AuthPage.tsx
  pages_tool_AuthPage_013: "CDK 用于开通游戏档案，可稍后在账号页兑换，不影响注册。",
} as const
