export const balanceCopy = {
  nav: '积分',
  eyebrow: '账号积分',
  title: '积分余额',
  description: '积分可用于网站内的付费功能，长期有效；积分不是现金，不能提现或转给其他账号。',
  available: '当前可用',
  reserved: '计算中暂扣',
  debt: '待补扣积分',
  lifetime_credited: '累计获得积分',
  unit: '积分',
  redeem_title: '兑换积分 CDK',
  redeem_description: '输入积分 CDK，兑换成功后积分会立即加入当前账号。',
  redeem_placeholder: '输入积分 CDK',
  redeem: '确认兑换',
  redeeming: '兑换中…',
  redeem_success: '兑换成功',
  history: '积分明细',
  empty: '还没有积分记录。',
  load_more: '查看更多记录',
  loading: '正在加载积分…',
  load_failed: '暂时无法加载积分，请稍后重试。',
  retry: '重试',
  go_to_redeem: '前往账号兑换页',
  cdk_credit: '积分 CDK 兑换',
  admin_credit: '管理员发放',
  admin_debit: '管理员扣除',
  schedule_debit: '主排班扣费',
  admin_credit_reversal: '管理员撤销发放',
  debt_repayment: '补扣积分',
} as const
