export const featuresCopy = {
  loading: '正在获取服务开放状态…',
  load_failed_title: '暂时无法获取服务状态',
  load_failed_body: '为避免在状态未知时误开放功能，产品入口已暂时停用。请稍后重试。',
  retry: '重新获取',
  closed_title: '该功能暂未开放',
  closed_body: '管理员暂时关闭了这项功能。已有数据会保留，重新开放后可继续使用。',
  site_closed_title: '产品功能暂停服务',
  site_closed_body: '公开说明页面仍可访问；管理员重新开放后，现有账号、档案和任务将恢复使用。',
  back_home: '返回首页',
  account_safety: '账号与隐私安全',
  recovery: '找回或重置密码',
  paused: '暂未开放',
  schedule_read_only: '排班生成暂未开放；历史任务、进度和结果仍可查看，已有任务可取消。',
  account_safety_title: '账号与隐私安全',
  account_safety_body: '即使产品功能或登录暂停，持有有效会话的用户仍可申请账号注销或安全退出。',
  delete_title: '申请注销账号',
  delete_body: '注销申请会验证当前会话、邮箱和密码。提交后将退出当前账号。',
  email: '账号邮箱',
  password: '当前密码',
  delete_account: '申请注销',
  deleting: '正在提交…',
  delete_confirm: '确认提交账号注销申请？',
  delete_accepted_title: '注销申请已受理',
  delete_accepted_before: '账户将在 ',
  delete_accepted_after: ' 后进入永久删除流程。在此之前可使用邮件中的一次性链接撤销。',
  delete_email_queued: '撤销邮件已进入投递队列；若暂未收到，请稍后检查收件箱和垃圾邮件。',
  delete_email_sent: '撤销邮件已发送，请妥善保存邮件中的一次性链接。',
  delete_email_delayed: '撤销邮件投递暂时延迟，系统会自动重试并记录异常。',
  delete_accepted_leave: '返回首页',
  account_error_authentication: '当前会话已失效，请重新登录后再试。',
  account_error_conflict: '账户状态已发生变化，请刷新页面确认当前注销状态。',
  account_error_rate_limited: '请求过于频繁，请稍后再试。',
  account_error_rate_limited_before: '请求过于频繁，请在 ',
  account_error_rate_limited_after: ' 秒后重试。',
  account_error_unavailable: '账户数据服务暂时不可用，请稍后重试；若持续失败请联系支持。',
  logout: '安全退出',
  logout_done: '已退出当前账号。',
  feature_labels: {
    site: '全站业务',
    registration: '用户注册',
    login: '登录与普通会话',
    profiles: '账号档案与工作区',
    tools: '公开工具中心',
    cdk_redemption: 'CDK 兑换与升级',
    free_preview: '免费档案',
    schedule_generation: '排班生成',
    metered_billing: '按次排班与商用账户',
    depot_value: '基建价值分析',
    skland: '森空岛导入',
    invitations: '邀请与奖励',
    inventory: '背包与统一道具',
    onboarding_tasks: '新人任务',
    announcements: '公告',
  },
  admin_nav: '功能开关',
  admin_title: '全站功能开关',
  admin_description: '服务端会强制执行这些设置；关闭入口不会删除用户数据、会话或正在运行的任务。',
  admin_loading: '正在加载功能开关…',
  admin_load_failed: '加载功能开关失败。',
  admin_save_failed: '保存功能开关失败。',
  admin_saved: '功能开关已保存并立即生效。',
  admin_save: '保存功能开关',
  admin_saving: '保存中…',
  admin_reload: '重新加载',
  admin_reload_online: '重新加载线上配置',
  admin_conflict: '线上功能开关已被其他管理员更新，本次修改尚未保存。请重新加载后再编辑。',
  admin_discard_confirm: '重新加载将丢弃当前未保存的功能开关修改，是否继续？',
  admin_raw_on_effective_off: '开关已打开，但因上级功能关闭而暂时不可用。',
  admin_effective_on: '当前实际开放',
  admin_effective_off: '当前已关闭',
  admin_updated_at: '最近更新：',
  delete_failed: '提交账号注销申请失败。',
  admin_groups: {
    site: '全站',
    account: '账号与档案',
    scheduling: '排班',
    tools: '公开工具',
    community: '社区内容',
  },
} as const
