export const inventoryCopy = {
  nav: '背包',
  eyebrow: '统一道具系统',
  title: '背包',
  description: '查看道具批次、有效期和适用入口。需要绑定业务操作的券不能在这里直接消耗。',
  loading: '正在加载背包…',
  load_failed: '加载背包失败。',
  empty: '当前分类没有可用道具。',
  search: '按道具名称筛选',
  all: '全部',
  consumable: '消耗券',
  capacity: '档案扩容',
  packs: '礼包',
  license_vouchers: '账号兑换',
  permanent: '永久',
  expires: '最近到期：',
  quantity: '数量',
  details: '道具详情',
  batches: '有效期批次',
  context_only: '请在对应功能入口选择使用',
  choose_profile: '选择目标档案',
  use: '使用道具',
  open: '开启礼包',
  close: '关闭',
  processing: '处理中…',
  operation_done: '道具操作已完成。',
  rewards_received: '实际获得',
  tasks: '新人任务',
  claim: '领取奖励',
  claimed: '已领取',
  incomplete: '未完成',
  disabled: '暂未启用',
  claim_done: '新人任务奖励已领取。',
  lifetime_bound: '终身版档案已绑定，道具已消耗。',
  lifetime_use_help: '可直接创建空档案后上传 JSON，也可绑定森空岛导入；只有档案成功保存后才会消耗，取消或失败时道具保留。',
  lifetime_create_failed: '使用终身版兑换 CDK 创建档案失败。',
  lifetime_json_created: '终身版档案已创建，可打开档案上传 JSON。',
  lifetime_profile_name: '档案名称（可选）',
  lifetime_profile_name_placeholder: '默认名称：终身档案',
  lifetime_profile_note: '备注（可选）',
  lifetime_profile_note_placeholder: '用于区分游戏账号或数据来源',
  create_with_json: '使用 JSON 创建档案',
  limited_use_help: '用于已绑定森空岛的免费预览档案，高级权限将在 2026 年 8 月 20 日 00:00 自动结束。',
  bind_and_use: '绑定森空岛并使用',
  capacity_preview: '容量预览',
  current: '当前',
  after_use: '使用后',
  maximum: '上限',
  priority_coupon: '优先计算券',
  priority_coupon_help: '让本次主排班进入最高优先队列；失败、取消或最终超时会返还。',
  training_coupon: '练度诊断券',
  training_coupon_help: '为本次主排班开启升级建议、ROI 和养成成本诊断。',
  recompute_coupon: '追加重算券',
  recompute_coupon_help: '在 24 小时修订窗口内，突破一次免费修订次数上限。',
  coupon_available: '可用：',
  scenario_coupon: '情景推演券',
  scenario_coupon_help: '缺少永久情景推演权限时，解锁本次情景比较。',
  scenario_coupon_required: '当前档案需要使用一张情景推演券才能运行。',
  reorder_coupon: '调序检查券',
  reorder_coupon_help: '本月免费调序检查次数用尽后，增加一次调序检查。',
  reorder_quota_exhausted: '本月免费调序检查次数已用尽。',
  reorder_coupon_required: '请勾选使用调序检查券后再开始检查。',
  reorder_coupon_unavailable: '本月免费调序检查次数已用尽，且背包中没有可用的调序检查券。',
  inventory_refresh_failed: '暂时无法读取背包余额，道具选项可能不会显示。',
  archive_title: '结果封存区',
  archive_description: '封存结果不会被普通历史的滚动淘汰。',
  archive_empty: '封存区暂无结果。',
  archive_action: '封存',
  unarchive_action: '取消封存',
  delete_result: '删除结果',
  delete_result_confirm: '确定永久删除这条普通历史结果吗？此操作不可撤销。',
  archive_done: '结果已移入封存区。',
  unarchive_done: '结果已移回普通历史区。',
  delete_result_done: '普通历史结果已删除。',
  archive_full: '封存区已满，请先取消封存或使用结果封存夹扩容。',
  history_full_for_unarchive: '普通历史区已满，请先删除一个普通结果后再取消封存。',
  maa_export_failed: '导出 MAA JSON 失败。',
  full_result_export_failed: '下载完整计算数据失败。',
} as const
