export const inventoryCopy = {
  nav: '背包',
  eyebrow: '我的道具',
  title: '背包',
  description: '查看道具数量、用途和有效期。需要在特定功能中使用的道具，会提示对应入口。',
  loading: '正在加载背包…',
  refresh_failed: '暂时无法刷新道具数量，请稍后重试。',
  load_failed: '暂时无法加载背包，请稍后重试。',
  empty: '当前分类没有可用道具。',
  search: '按道具名称筛选',
  all: '全部',
  consumable: '消耗券',
  capacity: '档案扩容',
  packs: '礼包',
  license_vouchers: '账号兑换',
  permanent: '永久',
  expires: '最近到期：',
  quantity: '数量',
  details: '道具详情',
  batches: '按有效期查看',
  context_only: '请前往对应功能，在提交操作时选择使用',
  choose_profile: '选择目标档案',
  use: '使用道具',
  open: '开启礼包',
  close: '关闭',
  processing: '处理中…',
  operation_done: '操作成功。',
  rewards_received: '获得的道具',
  tasks: '新人任务',
  claim: '领取奖励',
  claimed: '已领取',
  incomplete: '未完成',
  disabled: '暂时不可领取',
  claim_done: '新人任务奖励已领取。',
  lifetime_bound: '终身版档案已创建，对应道具已使用。',
  lifetime_use_help: '可以创建空档案后上传 JSON，也可以绑定森空岛导入数据。只有档案创建成功后才会消耗道具；取消或失败时，道具仍会保留。',
  lifetime_create_failed: '暂时无法使用终身版兑换 CDK 创建档案，请稍后重试。',
  lifetime_json_created: '终身版档案已创建，可打开档案上传 JSON。',
  lifetime_profile_name: '档案名称（可选）',
  lifetime_profile_name_placeholder: '默认名称：终身档案',
  lifetime_profile_note: '备注（可选）',
  lifetime_profile_note_placeholder: '用于区分游戏账号或数据来源',
  create_with_json: '使用 JSON 创建档案',
  limited_use_help: '本次限时体验活动已结束，活动发放的限时 CDK 已无法继续使用。',
  limited_activation_done: (profileName: string, endsAt: string) => `「${profileName}」的高级版限时体验已生效，可立即使用高级功能；有效至 ${endsAt}。`,
  limited_profile_fallback: '目标档案',
  view_profiles: '查看账号档案',
  bind_and_use: '绑定森空岛并使用',
  capacity_preview: '容量预览',
  current: '当前',
  after_use: '使用后',
  maximum: '上限',
  priority_coupon: '优先计算券',
  priority_coupon_help: '让本次排班优先开始计算。任务失败、取消或最终超时时，道具会自动返还。',
  training_coupon: '练度诊断券',
  training_coupon_help: '为本次排班提供升级建议、收益分析和养成成本诊断。',
  recompute_coupon: '追加重算券（历史）',
  recompute_coupon_help: '免费预览现可按页面规则重新生成完整排班，此历史道具无需再使用。',
  coupon_available: '可用：',
  scenario_coupon: '情景推演券',
  scenario_coupon_help: '当前档案没有长期情景推演权限时，可用于完成一次情景比较。',
  scenario_coupon_required: '当前档案需要使用一张情景推演券才能运行。',
  inventory_refresh_failed: '暂时无法读取背包，道具选项当前不可用。',
  balances_load_failed: '暂时无法加载道具数量，请稍后重试。',
  priority_coupon_balance_load_failed: '暂时无法读取优先计算券数量，请稍后重试。',
  capacity_expansion_done: (previous: number, next: number, maximum: number) => `扩容已生效：${previous} → ${next}（上限 ${maximum}）。`,
  task_rewards_label: (title: string) => `${title}奖励`,
  expires_after_days: (days: number) => `领取后 ${days} 天`,
  recent_events: '最近道具记录',
  ledger_grant: '已获得',
  ledger_reserve: '使用中锁定',
  ledger_consume: '已使用',
  ledger_refund: '退回',
  ledger_revoke: '已收回',
  ledger_gift_open: '开启礼包',
  ledger_capacity_effective: '容量生效',
  archive_title: '结果封存区',
  archive_description: '封存后的结果不会随普通历史记录自动清理。',
  archive_empty: '封存区暂无结果。',
  archive_action: '封存',
  unarchive_action: '取消封存',
  delete_result: '删除结果',
  delete_result_confirm: '确定永久删除这条历史结果吗？删除后无法恢复。',
  archive_done: '结果已移入封存区。',
  unarchive_done: '结果已移回普通历史区。',
  delete_result_done: '普通历史结果已删除。',
  archive_full: '封存区已满，请先取消封存或使用结果封存夹扩容。',
  history_full_for_unarchive: '普通历史记录已满，请先删除一条记录，再取消封存。',
  maa_export_failed: '导出 MAA JSON 失败。',
  maa_export_coupon_confirm: (balance: number) => `当前档案没有长期 MAA 导出权限。本次导出会使用 1 张 MAA 导出体验券（背包中还有 ${balance} 张）。确定继续吗？`,
  maa_export_coupon_unavailable: '当前档案需要使用 MAA 导出体验券，但背包中没有可用道具。',
  maa_export_coupon_consumed: 'MAA JSON 已下载，并已消耗 1 张 MAA 导出体验券。',
  export_downloading: '正在准备下载…',
  result_data_incompatible: '这条排班结果版本过旧或数据不完整，暂时无法完整展示。',
  full_result_export_failed: '暂时无法下载完整计算数据，请稍后重试。',
} as const
