export const meteredCopy = {
  permission_label: '按次高级版',
  commercial_nav: '商用账户',
  pricing: {
    title: '按次排班与商用账户',
    personal_title: '普通按次',
    personal_price: (points: string) => `${points} 积分`,
    personal_description: '约 6 元/次，仅成功主排班扣费。每个账号终身最多一个个人按次档案；第 9 次左右起，总成本通常高于 49 元单账号终身版。',
    commercial_title: '商用按次',
    commercial_price: '600–900 积分/次',
    commercial_description: '累计获得 10,000 积分自动解锁。Lv1–Lv4 实扣依次为 900 / 800 / 700 / 600 积分；最低价不低于个人按次价。默认 100 个活跃、1,000 个总档案。',
    capabilities: '按次档案包含高级版单次结果、MAA JSON、完整计算 JSON、练度建议和 ROI，但不包含场景对比实验室或 trusted 优化器选项。档案仅可处理已获授权的数据，不得转售 MaaTool 账号或 CDK，档案和积分不可转让。',
    checking_availability: '正在确认按次计费开放状态…',
    unavailable: '暂未开放',
    availability_unavailable: '暂时无法确认按次计费开放状态，当前按未开放处理。',
  },
  balance: {
    redeem_failed: '兑换积分失败。',
    redeem_retry: '兑换积分失败。可直接重试，系统不会重复入账。',
    personal_price_label: '个人按次价格',
    personal_price_value: (points: string) => `${points} 积分/成功主排班`,
    commercial_label: '商用账户',
    next_level_label: '下一等级',
    commercial_debt: (level: number | null | undefined, debt: string) => `${level ? `Lv${level}` : '未解锁'} · 已暂停，待追偿 ${debt} 积分`,
    commercial_eligible: (level: number | null | undefined, charge: string) => `Lv${level} · ${charge} 积分/成功主排班`,
    commercial_locked: (remaining: string) => `未解锁 · 还差 ${remaining} 积分`,
    next_level: (remaining: string | null, threshold: string) => `还差 ${remaining} 积分（门槛 ${threshold}）`,
    transaction_balance: (balance: string) => `余额 ${balance}`,
  },
  personal_profiles: {
    open_failed: '开通个人按次档案失败。',
    create: '创建个人按次档案',
    title: '个人按次排班',
    description: '600 积分/次，仅成功主排班扣费。每个网站账号终身最多一个个人按次档案，可继续升级为 49 元单账号终身版。',
    convert: '转为个人按次',
  },
  commercial_profiles: {
    load_failed: '加载商用档案失败。',
    create_failed: '添加商用账号失败。',
    update_failed: '更新商用档案失败。',
    batch_failed: '批量归档商用档案失败。',
    batch_partial: '批量归档未全部完成，请刷新后重试。',
    batch_success: (count: number) => `已归档 ${count} 个商用档案。`,
    delete_confirm: (name: string) => `永久删除“${name}”及其工作区、任务、结果和凭据？此操作不可撤销。`,
    batch_confirm: (count: number) => `确认归档选中的 ${count} 个商用档案？`,
    eyebrow: '服务商账户',
    title: '商用账号管理',
    description: '点击“添加账号”创建独立档案，打开后可上传 JSON 或绑定森空岛；按成功主排班计费，且只能处理已获授权的数据。账号、档案和积分不可转让。',
    creating: '正在添加…',
    create: '添加账号',
    limits: (active: number, activeLimit: number, total: number, totalLimit: number) => `活跃 ${active} / ${activeLimit} · 总量 ${total} / ${totalLimit}`,
    suspended: (reason: string) => ` · 已暂停：${reason}`,
    default_suspension_reason: '管理员暂停',
    active_filter: '活跃档案',
    archived_filter: '已归档',
    search_placeholder: '搜索名称或备注',
    search: '搜索',
    retry: '重试',
    select_all_loaded: '全选当前已加载档案',
    archiving: '归档中…',
    batch_archive: (count: number) => `批量归档${count ? `（${count}）` : ''}`,
    loading: '正在加载商用档案…',
    select_profile: (name: string) => `选择 ${name}`,
    no_note: '暂无备注',
    edit: '编辑',
    name_label: '档案名称',
    note_label: '备注',
    name_required: '档案名称不能为空。',
    save: '保存',
    cancel: '取消',
    edit_success: '商用档案已更新。',
    open_workspace: '打开工作区',
    restore: '恢复',
    archive: '归档',
    permanent_delete: '永久删除',
    empty: '当前筛选下还没有商用账号，可点击上方“添加账号”开始。',
    load_more: '加载更多',
  },
  quote: {
    load_failed: '加载本次积分报价失败。',
    loading: '正在获取本次积分报价…',
    retry: '重新获取报价',
    insufficient: '积分余额不足，暂不能生成排班。',
    go_to_balance: '前往积分余额',
    changed: (previous: string, latest: string) => `报价已从 ${previous} 积分更新为 ${latest} 积分，请查看后再次点击生成以确认新价格。`,
    summary: (charge: string, available: string, tier: number | null, sufficient: boolean) => `本次成功主排班预计扣除 ${charge} 积分${tier ? `（商用 Lv${tier}）` : ''}；当前可用 ${available} 积分。${sufficient ? '提交后将先预留，失败或取消会自动释放。' : '余额不足，暂不能提交。'}`,
  },
  progress: {
    failed_title: '任务未完成',
    failed_released: '任务失败，积分预留已释放；修正问题后可重新提交。',
    failed: '任务失败，未生成可用结果。',
    ended: '已结束',
    settled: (charge: string, tier: number | null) => `已扣除 ${charge} 积分${tier ? ` · 商用 Lv${tier}` : ''}`,
    released: (charge: string, tier: number | null) => `预留已释放：${charge} 积分${tier ? ` · 商用 Lv${tier}` : ''}`,
    reserved: (charge: string, tier: number | null) => `已预留 ${charge} 积分${tier ? ` · 商用 Lv${tier}` : ''}`,
  },
} as const
