export const notificationsCopy = {
  qqbot: {
    title: 'QQ 排班通知',
    body: '绑定 QQ 并开启通知后，排班生成完成会由 QQ 机器人私聊提醒。符合 MAA 导出条件的排班会同时发送 JSON 文件；需要体验券时可在私聊中确认后下载。',
    unavailable: 'QQ 通知服务尚未开放，开放后即可绑定并接收提醒。',
    bound: (qq: string) => `已绑定 QQ：${qq}`,
    receive: '接收排班完成通知',
    unbind: '解除 QQ 绑定',
    unbindConfirm: '解除 QQ 绑定后将停止排班通知，并取消尚未发送的提醒。确认解除？',
    codeLabel: 'QQ 机器人绑定命令',
    bindingCommand: (code: string) => `绑定网站 ${code}`,
    codeHelp: (expires: string) => `将上面的命令私聊发送给 QQ 机器人。绑定码有效期至 ${expires}，只能使用一次。绑定后刷新状态，并主动开启通知。`,
    generate: '生成绑定码',
    regenerate: '重新生成绑定码',
    refresh: '刷新绑定状态',
    failed: 'QQ 通知设置失败，请稍后重试。',
  },
  title: '通知',
  triggerLabel: (count: number) => count > 0 ? `通知，${count} 条未读` : '通知，无未读消息',
  unreadLive: (count: number) => count > 0 ? `当前有 ${count} 条未读通知` : '所有通知均已读',
  markAllRead: '全部设为已读',
  markingAllRead: '正在标记',
  loading: '正在加载通知…',
  empty: '暂时没有通知。',
  loadError: '加载通知失败，请稍后重试。',
  updateError: '更新通知状态失败，请稍后重试。',
  retry: '重试',
  loadMore: '加载更多',
  loadingMore: '正在加载…',
  unread: '未读',
  receivedAt: '收到于 ',
  permanent: '永久有效',
  expiresAt: (value: string) => `有效期至 ${value}`,
  itemGrantTitle: '获得新道具',
  itemGrantSingleBody: (name: string, quantity: number) => `${name} ×${quantity}`,
  itemGrantMultipleBody: (count: number) => `本次共获得 ${count} 种道具`,
  apiLoginRequired: '请先登录。',
  apiMethodNotAllowed: '当前操作不受支持。',
  apiInternalError: '通知服务暂时不可用，请稍后重试。',
  apiInvalidLimit: '通知数量必须是 1 到 50 之间的整数。',
  apiInvalidCursor: '加载位置已失效，请重新打开通知列表。',
  apiNotFound: '通知不存在。',
} as const
