export const notificationsCopy = {
  title: '通知',
  triggerLabel: (count: number) => count > 0 ? `通知，${count} 条未读` : '通知，无未读消息',
  unreadLive: (count: number) => count > 0 ? `当前有 ${count} 条未读通知` : '所有通知均已读',
  markAllRead: '全部已读',
  markingAllRead: '正在标记',
  loading: '正在加载通知…',
  empty: '暂时没有通知。',
  loadError: '加载通知失败，请稍后重试。',
  updateError: '更新通知状态失败，请稍后重试。',
  retry: '重试',
  loadMore: '加载更多',
  loadingMore: '正在加载…',
  unread: '未读',
  receivedAt: '收到于 ',
  permanent: '永久有效',
  expiresAt: (value: string) => `有效期至 ${value}`,
  itemGrantTitle: '获得新道具',
  itemGrantSingleBody: (name: string, quantity: number) => `${name} ×${quantity}`,
  itemGrantMultipleBody: (count: number) => `本次共获得 ${count} 种道具`,
  apiLoginRequired: '请先登录。',
  apiMethodNotAllowed: '当前操作不受支持。',
  apiInternalError: '通知服务暂时不可用，请稍后重试。',
  apiInvalidLimit: '通知数量必须是 1 到 50 之间的整数。',
  apiInvalidCursor: '加载位置已失效，请重新打开通知列表。',
  apiNotFound: '通知不存在。',
} as const
