export const publicContentCopy = {
  pricing_comparison_presets: '基建预设',
  pricing_comparison_manual: '手动排班',
  legacy_pricing_preset_supported: '支持右满252',
  legacy_pricing_eyebrow: '公开 SKU',
  legacy_pricing_intro: '先了解完整权益与限制，再选择适合自己的版本。现在提供月卡、半年卡、年卡、终身卡，以及个人和商用积分单次排班。',
  retired_pricing_intro: '个人维护方案有 30 天、90 天、365 天和终身卡可选，每份方案绑定一个游戏 UID。偶尔使用或需要商用时，也可以选择积分单次排班。',
  retired_personal_disclosure: '个人按次档案仅限本人非商业使用；商用档案仅可处理数据权利人已授权的数据。',
  retired_commercial_disclosure: '商用主排班按成功任务计费；MaaTool 账号、CDK、档案和积分均不可转让或转售。',
  pricing_transfer_disclosure: 'MaaTool 账号、CDK 和档案均不可转让或转售。',
  retired_commercial_comparison: '批量报告导出 / 商用授权',
  retired_comparison_unavailable: '不支持',
  legacy_pricing_plans: {
    single_account_monthly: {
      label: '单账号月卡 CDK',
      badge: '低门槛',
      display_price: '6 元 / 31 天',
      original_price: '15 元 / 31 天',
      discount_fold: 4,
      summary: '完整高级排班能力，适合先按月维护单个游戏账号；到期后可续购或升级长期方案。',
      account_scope: '仅限一个游戏 UID，兑换后连续 31 天有效，不支持自行更换游戏账号',
    },
    single_account_half_year: {
      label: '单账号半年卡 CDK',
      badge: '高性价比',
      display_price: '19.6 元 / 183 天',
      original_price: '49 元 / 183 天',
      discount_fold: 4,
      summary: '完整高级排班能力，相比月卡降低约 46% 的月均成本，适合稳定使用半年的玩家。',
      account_scope: '仅限一个游戏 UID，兑换后连续 183 天有效，不支持自行更换游戏账号',
    },
    single_account_annual: {
      label: '单账号年卡 CDK',
      badge: '年度推荐',
      display_price: '31.6 元 / 365 天',
      original_price: '79 元 / 365 天',
      discount_fold: 4,
      summary: '完整高级排班能力，默认 4 折活动价月均约 2.6 元；适合长期维护同一账号并持续导出结果的玩家。',
      account_scope: '仅限一个游戏 UID，兑换后连续 365 天有效，不支持自行更换游戏账号',
    },
    single_account_lifetime: {
      label: '单账号终身卡 CDK',
      badge: '长期方案',
      display_price: '51.6 元 / 长期',
      original_price: '129 元 / 长期',
      discount_fold: 4,
      summary: '一次购买即可长期使用完整高级能力，包含持续重新生成、MAA JSON、完整数据下载、高级分析、练度建议和自定义配置。',
      account_scope: '仅限长期维护同一个游戏 UID，不支持自行更换游戏账号',
    },
  },
  validation_pricing_price_format: '原价必须使用“数字 元 / 有效期”的格式。',
  default_pricing_badge_monthly: '尝鲜维护',
  default_pricing_badge_half_year: '版本推荐',
  default_pricing_badge_annual: '年度方案',
  default_pricing_badge_lifetime: '长期方案',
  default_lifetime_upgrade_fee: '3 元',
  admin_lifetime_upgrade: '补差价升级终身卡',
  admin_lifetime_upgrade_description: '设置闲鱼升级商品链接和手续费，原订单与补款金额由客服核对。',
  admin_lifetime_upgrade_purchase_url: '升级商品链接',
  admin_lifetime_upgrade_service_fee: '升级手续费',
  default_qq_name: 'MaaTool 官方 QQ 群',
  default_qq_link_label: '加入 QQ 群',
  faq_join_question: '如何加入 MaaTool QQ 交流群？',
  faq_join_answer: '点击页面中的“加入 QQ 群”申请入群。反馈问题前，先遮盖截图中的个人信息；不要发送密码、完整 CDK、二维码、Cookie 或森空岛凭据。',
  legacy_faq: {
    intro: '查找账号、CDK、森空岛导入和 MAA JSON 的使用说明，以及隐私与售后问题的处理方式。',
    cta_heading: '需要帮助？',
    cta_body: '请带上问题描述、复现步骤和不含敏感信息的截图到交流群反馈。',
    items: [
      { id: 'requirements', question: '使用 MaaTool 需要准备什么？', answer: '只想查看仓库估值时，可以直接使用免费工具。生成个人排班有两种方式：通过森空岛确认游戏 UID 后创建免费档案，或注册 MaaTool 账号并使用 CDK 开通正式游戏账号档案。随后按工作台提示导入干员数据、核对基建配置并生成结果。', action: 'none' },
      { id: 'account-concepts', question: 'MaaTool 账号、游戏账号档案和 CDK 分别是什么？', answer: 'MaaTool 账号用于登录本站；游戏账号档案是工作台中绑定某个《明日方舟》游戏 UID、保存数据和排班结果的工作区；CDK 用于开通正式档案及对应权益。三者用途不同，CDK 和档案都不是你的 MaaTool 登录密码或游戏密码。', action: 'none' },
      { id: 'game-password', question: '使用森空岛导入需要提供《明日方舟》游戏密码吗？', answer: '不需要。森空岛导入通过二维码或授权凭据确认可读取的角色，不会要求你提供《明日方舟》游戏密码。二维码和授权凭据具有敏感性，只应在 MaaTool 的授权界面中使用，不要发送到 QQ 群或其他公开渠道。', action: 'none' },
      { id: 'free-versus-lifetime', question: '免费档案和单账号终身版有什么区别？', answer: '免费档案通过森空岛确认 UID 后领取，一个游戏 UID 全站只能领取一次，可生成并查看完整游戏内轮换；轻量 MAA JSON 按有效高级体验期或导出体验券规则下载，完整计算数据和高级分析随高级权限开放。30 天尝鲜维护包、90 天版本维护卡、365 天年度维护卡和终身卡均可选择森空岛导入或 MAA 干员 JSON 初始化，按购买时长提供完整高级能力；具体期限、价格与权益以价格与权益页为准。', action: 'none' },
      { id: 'cdk-account', question: 'CDK 和游戏账号有什么关系？', answer: 'CDK 用于开通正式游戏账号档案和对应功能，不能用于登录，也不是游戏账号。兑换后，请导入你有权处理的游戏数据。不要向他人发送完整 CDK 或订单信息。', action: 'none' },
      { id: 'skland-data', question: '森空岛导入会读取什么数据？', answer: '森空岛授权后，MaaTool 会先读取角色列表并展示账号预览。你确认角色后，才会保存绑定并导入排班所需的游戏 UID、昵称、干员、养成库存和基建配置等数据。免费档案的干员数据只能通过森空岛更新；正式 CDK 档案还可使用 MAA 干员识别文件。', action: 'none' },
      { id: 'skland-save', question: '森空岛授权后会立即保存账号吗？', answer: '不会在读取到授权后立即绑定。MaaTool 会先展示可用角色和账号预览，只有你确认所选角色后，才保存绑定并导入数据。用于持续导入的森空岛凭据会在服务端加密保存；你也可以在账号设置中清除凭据，但这不会解除已经确认的游戏 UID 绑定。', action: 'none' },
      { id: 'skland-refresh', question: '游戏数据变化后，排班会自动实时更新吗？', answer: '不会把游戏中的每次变化自动更新为新排班。计算使用工作台最近一次成功导入的数据；干员练度、库存或基建配置变化后，请先重新导入或刷新森空岛数据，核对账号与更新时间，再重新计算。已有结果仍以生成时的数据为准。', action: 'none' },
      { id: 'use-json', question: '生成的 JSON 应该如何使用？', answer: '在支持导出的结果页下载轻量 MAA JSON，然后在 MAA 的自定义基建配置中选择该文件。它只包含班次、房间、入驻干员、产品和自动执行动作；完整计算 JSON 是高级版的分析与排障数据，不应导入 MAA。使用前请核对 MAA 版本、游戏内房间布局和当前干员状态，并保留原有配置以便恢复。游戏内轮换模式不会生成 MAA JSON。', action: 'none' },
      { id: 'json-unavailable', question: '为什么结果页没有 MAA JSON 下载？', answer: '轻量 MAA JSON 下载同时取决于档案权益和排班模式：正式档案可直接导出，免费档案按有效高级体验期或导出体验券规则使用，且结果必须采用 MAA 排班模式。游戏内轮换不会生成 MAA JSON。完整计算 JSON 是另一项高级版下载，可用于普通历史、封存历史和轮换结果的分析与排障，但不应导入 MAA。', action: 'none' },
      { id: 'schedule-modes', question: 'MAA 排班和游戏内轮换有什么区别？', answer: 'MAA 排班面向 MAA 的自定义基建执行流程，在档案具备导出权益时可生成 MAA JSON。游戏内轮换会生成两班设施预设队列，供你在游戏内使用队列轮换或快速切换，不依赖 MAA JSON。选择前请按自己的执行方式和换班频率判断。', action: 'none' },
      { id: 'result-differences', question: '为什么结果与实际收益不同？', answer: '结果按最近一次成功导入的数据、基建配置和规则参数测算，不保证实际收益。游戏版本、干员状态、订单波动、心情、实际换班时间和 MAA 配置都可能造成偏差。等效理智用于比较不同产出，不是游戏实际发放的理智。', action: 'none' },
      { id: 'depot-versus-schedule', question: '免费仓库估值和排班功能有什么区别？', answer: '仓库估值用等效理智估算库存价值。个人排班根据干员、房间、生产目标和策略生成方案及相关指标。MAA JSON 按档案权益、体验期或体验券规则导出；完整计算 JSON 是高级版单独提供的分析与排障文件。', action: 'none' },
      { id: 'import-failure', question: '授权或导入失败怎么办？', answer: '先记录报错时间和提示，再确认网络、森空岛登录状态及所选角色是否与当前档案的 UID 一致。授权过期或凭据失效时，请按页面提示重新授权同一账号；第三方服务暂时异常时可稍后重试。问题持续时，请携带操作步骤和不含敏感信息的报错截图到 QQ 群反馈。', action: 'none' },
      { id: 'change-bound-account', question: '绑定后可以自行更换游戏 UID 吗？', answer: '不可以自行更换。免费档案绑定确认时选择的游戏 UID；30 天尝鲜维护包、90 天版本维护卡、365 天年度维护卡和终身卡无论使用森空岛还是 JSON 初始化，都仅用于同一个游戏账号。预览阶段发现角色不对时请不要确认，返回后重新选择；已经绑定或被异常拦截时，请通过 MaaTool 官方 QQ 群申请人工核验，不要重复尝试导入其他账号。', action: 'none' },
      { id: 'data-security', question: 'MaaTool 如何保护账号和授权数据？', answer: 'MaaTool 登录密码经过不可逆处理后保存，不会保存明文；用于持续导入的森空岛凭据会加密保存。服务不会出售个人信息，也不会将游戏数据用于与服务无关的广告投放。任何网络服务都无法保证绝对安全，请勿共享密码、完整 CDK、二维码、Cookie 或授权凭据。', action: 'none' },
      { id: 'delete-account', question: '如何删除我的账号和数据？', answer: '请通过 MaaTool 官方 QQ 群申请删除 MaaTool 账号及相关工作台数据。为防止他人冒用，处理前可能需要完成必要的身份核验；请勿在群内发送密码、完整 CDK、二维码、Cookie 或森空岛凭据。', action: 'none' },
      { id: 'support-info', question: '联系客服时需要提供哪些信息？', answer: '请提供账号标识、订单或 CDK 的安全标识、报错时间、不含敏感信息的错误描述、操作步骤，以及相关浏览器、MAA 或游戏版本。截图应先遮盖个人信息。不要发送密码、完整 CDK、二维码、Cookie 或森空岛凭据；材料齐全后，客服会按支持页说明的时限首次响应。', action: 'none' },
      { id: 'qq-group', question: '如何加入 MaaTool QQ 交流群？', answer: '可通过页面中的入群按钮申请加入。反馈问题时，请先遮盖个人信息，并且不要发送密码、完整 CDK、二维码、Cookie 或森空岛凭据。', action: 'qq_group' },
    ],
  },
  thanks_title: '致谢',
  thanks_eyebrow: '项目与协助者',
  thanks_intro: 'MaaTool 参考了以下开源项目和社区资料。感谢参与开发、测试和反馈的每一位协助者。',
  thanks_data_heading: '数据与社区项目',
  thanks_data_intro: '这些项目帮助我们核对数据和规则、兼容文件格式，并验证功能。',
  thanks_yituliu_name: '一图流',
  thanks_yituliu_description: '为材料价值和相关数据核对提供公开参考。',
  thanks_penguin_name: '企鹅物流',
  thanks_penguin_description: '帮助兼容仓库数据格式，提供材料数据交流资料。',
  thanks_prts_name: 'PRTS Wiki',
  thanks_prts_description: '为基建技能规则的核对与验证提供社区资料。',
  thanks_maa_name: 'MAA',
  thanks_maa_description: '提供干员数据导入和自定义基建配置所需的开放格式与工具。',
  thanks_developer_heading: '开发者',
  thanks_developer_intro: '负责项目设计、开发和长期维护。',
  thanks_developer_name: 'ntgmc',
  thanks_legacy_developer_name: '铃语',
  thanks_developer_description: 'MaaTool 开发与维护。',
  thanks_github_avatar_alt: '{name} 的 GitHub 头像',
  thanks_helpers_heading: '协助开发 / 测试',
  thanks_helpers_intro: '感谢帮助复现问题、测试方案和提出使用建议的协助者。',
  thanks_helpers_name: 'DaKe.',
  thanks_legacy_helpers_name: '所有参与开发、测试、反馈与验证的协助者',
  thanks_legacy_helpers_description: '每一次复现、建议、测试和反馈都让 MaaTool 更可靠。',
  admin_nav: '公开内容',
  admin_title: '公开内容管理',
  admin_description: '编辑 QQ 群、CDK 购买链接、常见问题、价格与权益和致谢页。保存后，用户新打开或刷新的页面会显示更新。',
  admin_display_only_warning: '这里修改页面显示的价格、原价和折扣。CDK 权限、商品功能、授权规则和风控策略仍由系统配置决定。',
  admin_loading: '正在加载公开内容…',
  admin_load_failed: '加载公开内容失败。',
  admin_save_failed: '保存公开内容失败。',
  admin_saved: '公开内容已保存并发布。',
  admin_saving: '保存中…',
  admin_save: '保存并发布',
  admin_reload: '重新加载',
  admin_reload_online: '重新加载线上配置',
  admin_conflict: '线上公开内容已被其他管理员更新，本次草稿尚未发布。请重新加载后再编辑。',
  admin_discard_confirm: '重新加载将丢弃当前未保存的公开内容草稿，是否继续？',
  admin_duplicate_id: '条目标识重复，请删除重复条目后重新添加。',
  admin_limit_reached: (limit: number) => `已达到最多 ${limit} 项的上限。`,
  status_loading_fallback: '最新页面内容正在加载，部分信息可能稍后更新。',
  status_loading_cached: '正在获取最新页面内容，当前信息可继续查看。',
  status_error_fallback: '最新页面内容暂时无法加载，部分信息可能不是最新版本。',
  status_error_cached: '页面内容暂时无法更新，当前信息可继续查看。',
  status_retry: '重新加载',
  admin_updated_at: '最近发布：',
  admin_tabs_label: '公开内容分区',
  admin_tab_qq: 'QQ群',
  admin_tab_purchase: 'CDK 购买',
  admin_tab_faq: '常见问题',
  admin_tab_pricing: '价格与权益',
  admin_tab_thanks: '致谢',
  admin_required: '必填',
  admin_qq_description: '页脚、常见问题、客服页和价格页会使用这里设置的入群信息。',
  admin_qq_name: '群名称',
  admin_qq_number: '群号',
  admin_qq_url: 'HTTPS 入群链接',
  admin_qq_link_label: '按钮文案',
  admin_purchase_description: '配置主页和工具页显示的闲鱼 CDK 购买入口。仅支持 HTTPS；留空将隐藏这两个入口。',
  admin_xianyu_url: '闲鱼购买链接',
  admin_page_eyebrow: '页眉短标签',
  admin_page_title: '页面标题',
  admin_page_intro: '页面介绍',
  admin_faq_cta_heading: 'FAQ 底部标题',
  admin_faq_cta_body: 'FAQ 底部说明',
  admin_faq_items: 'FAQ 条目',
  admin_add_faq: '新增 FAQ',
  admin_question: '问题',
  admin_answer: '答案',
  admin_show_qq_action: '附加入 QQ 群按钮',
  admin_pricing_plans: '价格方案与有效期',
  admin_pricing_plans_description: '价格页将四种个人维护方案放在同一张卡片中。分别设置 30 天、90 天、365 天和终身方案的价格与说明。',
  admin_plan_label: '方案名称',
  admin_plan_badge: '方案徽标',
  admin_plan_original_price: '原价（含单位和有效期）',
  admin_plan_purchase_url: '购买链接',
  admin_plan_discount_fold: '折扣（折）',
  admin_plan_effective_price: '当前折后展示价',
  admin_plan_summary: '方案摘要',
  admin_plan_scope: '账号范围',
  admin_policy_heading: '公开说明标题',
  admin_disclosures: '公开说明',
  admin_add_disclosure: '新增说明',
  admin_comparison_heading: '权益对比标题',
  admin_comparison_rows: '权益对比行',
  admin_add_comparison: '新增对比行',
  admin_feature_name: '权益名称',
  admin_free_preview: '免费预览',
  admin_single_lifetime: '单账号终身版',
  admin_support_heading: '客服区标题',
  admin_support_body: '客服区说明',
  admin_thanks_sections: '致谢分组',
  admin_add_section: '新增分组',
  admin_section_heading: '分组标题',
  admin_section_intro: '分组说明',
  admin_entries: '致谢条目',
  admin_add_entry: '新增条目',
  admin_entry_name: '名称',
  admin_entry_description: '说明',
  admin_entry_url: '可选 HTTPS 链接',
  admin_entry_avatar_url: '头像地址（HTTPS 或 /assets/ 站内路径）',
  admin_move_up: '上移',
  admin_move_down: '下移',
  admin_delete: '删除',
  admin_empty_list: '当前没有条目，可使用上方按钮新增。',
  admin_drag_handle: '拖动排序',
  admin_drag_instructions: '按空格键抓取条目，使用方向键调整位置，再按空格键放下；按 Escape 取消。',
  admin_select_item: '选择左侧条目，查看或编辑详情。',
  admin_untitled: '未命名条目',
  admin_list_order_help: '拖动手柄调整显示顺序，选择条目后在右侧编辑详情。',
  validation_invalid: '公开内容配置无效。',
} as const
