export const publicContentCopy = {
  legacy_pricing_eyebrow: '公开 SKU',
  legacy_pricing_intro: '先了解完整权益与限制，再选择适合自己的版本。现在提供月卡、半年卡、年卡、终身卡，以及个人和商用积分单次排班。',
  validation_pricing_price_format: '原价必须使用“数字 元 / 有效期”的格式。',
  default_pricing_badge_monthly: '低门槛',
  default_pricing_badge_half_year: '高性价比',
  default_pricing_badge_annual: '年度推荐',
  default_pricing_badge_lifetime: '长期方案',
  default_qq_name: 'MaaTool 官方 QQ 群',
  default_qq_link_label: '加入 QQ 群',
  faq_join_question: '如何加入 MaaTool QQ 交流群？',
  faq_join_answer: '可通过页面中的入群按钮申请加入。反馈问题时，请先遮盖个人信息，并且不要发送密码、完整 CDK、二维码、Cookie 或森空岛凭据。',
  thanks_title: '致谢',
  thanks_eyebrow: '共同建设',
  thanks_intro: 'MaaTool 的数据参考、格式兼容和持续改进离不开开源项目、社区资料以及每一位参与开发、测试和反馈的协助者。',
  thanks_data_heading: '数据与社区项目',
  thanks_data_intro: '感谢这些项目和社区资料为数据核对、格式兼容与功能验证提供帮助。',
  thanks_yituliu_name: '一图流',
  thanks_yituliu_description: '为材料价值和相关数据核对提供公开参考。',
  thanks_penguin_name: '企鹅物流',
  thanks_penguin_description: '为仓库数据格式兼容和材料数据交流提供社区基础。',
  thanks_prts_name: 'PRTS Wiki',
  thanks_prts_description: '为基建技能规则的核对与验证提供社区资料。',
  thanks_maa_name: 'MAA',
  thanks_maa_description: '为干员数据导入和自定义基建配置生态提供开放格式与工具基础。',
  thanks_developer_heading: '开发者',
  thanks_developer_intro: '感谢项目的设计、实现和长期维护。',
  thanks_developer_name: 'ntgmc',
  thanks_legacy_developer_name: '铃语',
  thanks_developer_description: 'MaaTool 开发与维护。',
  thanks_github_avatar_alt: '{name} 的 GitHub 头像',
  thanks_helpers_heading: '协助开发 / 测试',
  thanks_helpers_intro: '感谢所有帮助发现问题、验证方案并推动体验改进的人。',
  thanks_helpers_name: 'DaKe.',
  thanks_legacy_helpers_name: '所有参与开发、测试、反馈与验证的协助者',
  thanks_legacy_helpers_description: '每一次复现、建议、测试和反馈都让 MaaTool 更可靠。',
  admin_nav: '公开内容',
  admin_title: '公开内容管理',
  admin_description: '集中维护 QQ 群、CDK 购买链接、常见问题、价格与权益展示和致谢页。保存成功后立即对新打开或刷新的前台页面生效。',
  admin_display_only_warning: '用于维护公开价格展示、原价和折扣；CDK 实际权限、SKU 能力、真实授权规则与风控策略由系统配置决定。',
  admin_loading: '正在加载公开内容…',
  admin_load_failed: '加载公开内容失败。',
  admin_save_failed: '保存公开内容失败。',
  admin_saved: '公开内容已保存并发布。',
  admin_saving: '保存中…',
  admin_save: '保存并发布',
  admin_reload: '重新加载',
  admin_reload_online: '重新加载线上配置',
  admin_conflict: '线上公开内容已被其他管理员更新，本次草稿尚未发布。请重新加载后再编辑。',
  admin_discard_confirm: '重新加载将丢弃当前未保存的公开内容草稿，是否继续？',
  admin_duplicate_id: '条目标识重复，请删除重复条目后重新添加。',
  admin_limit_reached: (limit: number) => `已达到最多 ${limit} 项的上限。`,
  status_loading_fallback: '正在加载最新站点内容，当前暂时显示内置内容。',
  status_loading_cached: '正在刷新站点内容，当前继续显示上次成功加载的内容。',
  status_error_fallback: '动态内容暂时无法加载，当前显示内置默认内容，信息可能不是最新版本。',
  status_error_cached: '刷新失败，当前显示上次成功加载的内容。',
  status_retry: '重新加载',
  admin_updated_at: '最近发布：',
  admin_tabs_label: '公开内容分区',
  admin_tab_qq: 'QQ群',
  admin_tab_purchase: 'CDK 购买',
  admin_tab_faq: '常见问题',
  admin_tab_pricing: '价格与权益',
  admin_tab_thanks: '致谢',
  admin_required: '必填',
  admin_qq_description: '该配置会同步用于公共页脚、FAQ、客服页和价格页的入群入口。',
  admin_qq_name: '群名称',
  admin_qq_number: '群号',
  admin_qq_url: 'HTTPS 入群链接',
  admin_qq_link_label: '按钮文案',
  admin_purchase_description: '配置主页和工具页显示的闲鱼 CDK 购买入口。仅支持 HTTPS；留空将隐藏这两个入口。',
  admin_xianyu_url: '闲鱼购买链接',
  admin_page_eyebrow: '页眉短标签',
  admin_page_title: '页面标题',
  admin_page_intro: '页面介绍',
  admin_faq_cta_heading: 'FAQ 底部标题',
  admin_faq_cta_body: 'FAQ 底部说明',
  admin_faq_items: 'FAQ 条目',
  admin_add_faq: '新增 FAQ',
  admin_question: '问题',
  admin_answer: '答案',
  admin_show_qq_action: '附加入 QQ 群按钮',
  admin_pricing_plans: 'Pricing 方案与有效期',
  admin_pricing_plans_description: '前台会将四种单账号 CDK 合并为一个定价方案；以下字段分别控制月卡、半年卡、年卡和终身卡的有效期价格与文案。',
  admin_plan_label: '方案名称',
  admin_plan_badge: '方案徽标',
  admin_plan_original_price: '原价（含单位和有效期）',
  admin_plan_discount_fold: '折扣（折）',
  admin_plan_effective_price: '当前折后展示价',
  admin_plan_summary: '方案摘要',
  admin_plan_scope: '账号范围',
  admin_policy_heading: '公开说明标题',
  admin_disclosures: '公开说明',
  admin_add_disclosure: '新增说明',
  admin_comparison_heading: '权益对比标题',
  admin_comparison_rows: '权益对比行',
  admin_add_comparison: '新增对比行',
  admin_feature_name: '权益名称',
  admin_free_preview: '免费预览',
  admin_single_lifetime: '单账号终身版',
  admin_support_heading: '客服区标题',
  admin_support_body: '客服区说明',
  admin_thanks_sections: '致谢分组',
  admin_add_section: '新增分组',
  admin_section_heading: '分组标题',
  admin_section_intro: '分组说明',
  admin_entries: '致谢条目',
  admin_add_entry: '新增条目',
  admin_entry_name: '名称',
  admin_entry_description: '说明',
  admin_entry_url: '可选 HTTPS 链接',
  admin_entry_avatar_url: '头像地址（HTTPS 或 /assets/ 站内路径）',
  admin_move_up: '上移',
  admin_move_down: '下移',
  admin_delete: '删除',
  admin_empty_list: '当前没有条目，可使用上方按钮新增。',
  admin_drag_handle: '拖动排序',
  admin_drag_instructions: '按空格键抓取条目，使用方向键调整位置，再按空格键放下；按 Escape 取消。',
  admin_select_item: '请从左侧列表选择一个条目查看和编辑详细内容。',
  admin_untitled: '未命名条目',
  admin_list_order_help: '拖动手柄可改变展示顺序；点选条目后在右侧编辑详细内容。',
  validation_invalid: '公开内容配置无效。',
} as const
