export const publicContentCopy = {
  default_qq_name: 'MaaTool 官方 QQ 群',
  default_qq_link_label: '加入 QQ 群',
  faq_join_question: '如何加入 MaaTool QQ 交流群？',
  faq_join_answer: '可通过页面中的入群按钮申请加入。反馈问题时，请先遮盖个人信息，并且不要发送密码、完整 CDK、二维码、Cookie 或森空岛凭据。',
  thanks_title: '致谢',
  thanks_eyebrow: '共同建设',
  thanks_intro: 'MaaTool 的数据参考、格式兼容和持续改进离不开开源项目、社区资料以及每一位参与开发、测试和反馈的协助者。',
  thanks_data_heading: '数据与社区项目',
  thanks_data_intro: '感谢这些项目和社区资料为数据核对、格式兼容与功能验证提供帮助。',
  thanks_yituliu_name: '一图流',
  thanks_yituliu_description: '为材料价值和相关数据核对提供公开参考。',
  thanks_penguin_name: '企鹅物流',
  thanks_penguin_description: '为仓库数据格式兼容和材料数据交流提供社区基础。',
  thanks_prts_name: 'PRTS Wiki',
  thanks_prts_description: '为基建技能规则的核对与验证提供社区资料。',
  thanks_maa_name: 'MAA',
  thanks_maa_description: '为干员数据导入和自定义基建配置生态提供开放格式与工具基础。',
  thanks_developer_heading: '开发者',
  thanks_developer_intro: '感谢项目的设计、实现和长期维护。',
  thanks_developer_name: '铃语',
  thanks_developer_description: 'MaaTool 开发与维护。',
  thanks_helpers_heading: '协助开发 / 测试',
  thanks_helpers_intro: '感谢所有帮助发现问题、验证方案并推动体验改进的人。',
  thanks_helpers_name: '所有参与开发、测试、反馈与验证的协助者',
  thanks_helpers_description: '每一次复现、建议、测试和反馈都让 MaaTool 更可靠。',
  admin_nav: '公开内容',
  admin_title: '公开内容管理',
  admin_description: '集中维护 QQ 群、常见问题、价格与权益展示和致谢页。保存成功后立即对新打开或刷新的前台页面生效。',
  admin_display_only_warning: '这里只修改公开展示，不会改变 CDK 实际权限、SKU 能力、真实授权规则或风控策略。',
  admin_loading: '正在加载公开内容…',
  admin_load_failed: '加载公开内容失败。',
  admin_save_failed: '保存公开内容失败。',
  admin_saved: '公开内容已保存并发布。',
  admin_saving: '保存中…',
  admin_save: '保存并发布',
  admin_reload: '重新加载',
  admin_updated_at: '最近发布：',
  admin_tabs_label: '公开内容分区',
  admin_tab_qq: 'QQ群',
  admin_tab_faq: '常见问题',
  admin_tab_pricing: '价格与权益',
  admin_tab_thanks: '致谢',
  admin_required: '必填',
  admin_qq_description: '该配置会同步用于公共页脚、FAQ、客服页和价格页的入群入口。',
  admin_qq_name: '群名称',
  admin_qq_number: '群号',
  admin_qq_url: 'HTTPS 入群链接',
  admin_qq_link_label: '按钮文案',
  admin_page_eyebrow: '页眉短标签',
  admin_page_title: '页面标题',
  admin_page_intro: '页面介绍',
  admin_faq_cta_heading: 'FAQ 底部标题',
  admin_faq_cta_body: 'FAQ 底部说明',
  admin_faq_items: 'FAQ 条目',
  admin_add_faq: '新增 FAQ',
  admin_question: '问题',
  admin_answer: '答案',
  admin_show_qq_action: '附加入 QQ 群按钮',
  admin_pricing_plans: '固定公开方案',
  admin_plan_label: '方案名称',
  admin_plan_badge: '方案徽标',
  admin_plan_price: '展示价格',
  admin_plan_summary: '方案摘要',
  admin_plan_scope: '账号范围',
  admin_policy_heading: '公开说明标题',
  admin_disclosures: '公开说明',
  admin_add_disclosure: '新增说明',
  admin_comparison_heading: '权益对比标题',
  admin_comparison_rows: '权益对比行',
  admin_add_comparison: '新增对比行',
  admin_feature_name: '权益名称',
  admin_free_preview: '免费预览',
  admin_single_lifetime: '单账号终身版',
  admin_support_heading: '客服区标题',
  admin_support_body: '客服区说明',
  admin_thanks_sections: '致谢分组',
  admin_add_section: '新增分组',
  admin_section_heading: '分组标题',
  admin_section_intro: '分组说明',
  admin_entries: '致谢条目',
  admin_add_entry: '新增条目',
  admin_entry_name: '名称',
  admin_entry_description: '说明',
  admin_entry_url: '可选 HTTPS 链接',
  admin_move_up: '上移',
  admin_move_down: '下移',
  admin_delete: '删除',
  admin_empty_list: '当前没有条目，可使用上方按钮新增。',
  validation_invalid: '公开内容配置无效。',
} as const
