export const statusCopy = {
  // src/pages/StatusPage.tsx
  pages_StatusPage_001: "MaaTool 官方",
  pages_StatusPage_002: "服务状态",
  pages_StatusPage_003: "实时查看网站与排班计算服务的运行状态和可用性。",
  pages_StatusPage_004: "返回首页",
  pages_StatusPage_005: "进入工作台",
  pages_StatusPage_006: "最近更新",
  pages_StatusPage_007: "自动刷新",
  pages_StatusPage_008: "服务组件",
  pages_StatusPage_009: "排班优化计算",
  pages_StatusPage_010: "提供排班、优化建议与场景分析服务。",
  pages_StatusPage_011: "等待任务",
  pages_StatusPage_012: "运行中",
  pages_StatusPage_013: "并发容量",
  pages_StatusPage_015: "状态判定",
  pages_StatusPage_016: "有空闲并发槽且没有等待任务",
  pages_StatusPage_017: "等待任务少于 5 个",
  pages_StatusPage_018: "等待任务达到 5 个或更多",
  pages_StatusPage_019: "服务或 Worker 不可用",
  pages_StatusPage_021: "状态暂时无法获取",
  pages_StatusPage_022: "无法连接到状态接口，请稍后重试。",
  pages_StatusPage_023: "重新检查",
  pages_StatusPage_024: "正在读取服务状态…",
  pages_StatusPage_025: "深绿色",
  pages_StatusPage_026: "绿色",
  pages_StatusPage_027: "黄色",
  pages_StatusPage_028: "红色",
  pages_StatusPage_029: "个",
  pages_StatusPage_030: "个并发槽",
  pages_StatusPage_031: "数据来自实时 Worker 注册表和优化队列快照；页面不会展示任务、用户或档案明细。",
  pages_StatusPage_032: "当前服务运行正常，队列中没有等待任务。",
  pages_StatusPage_033: "服务运行正常，但有少量任务正在排队。",
  pages_StatusPage_034: "队列正在积压，处理时间可能延长。",
  pages_StatusPage_035: "服务暂时不可用，请稍后重试。",
  pages_StatusPage_036: "历史可用性",
  pages_StatusPage_037: "过去 30 天",
  pages_StatusPage_038: "每个方格代表一个小时，并按 Asia/Shanghai 展示。",
  pages_StatusPage_039: "已采集",
  pages_StatusPage_040: "个样本。",
  pages_StatusPage_041: "部分历史数据暂不可用，灰色方格表示没有采样。",
  pages_StatusPage_042: "状态图例",
  pages_StatusPage_043: "过去 30 天每小时状态",
  pages_StatusPage_044: "事件时间线",
  pages_StatusPage_045: "服务事件",
  pages_StatusPage_046: "过去 30 天没有公开事件。",
  pages_StatusPage_047: "开始于",
  pages_StatusPage_048: "样本",
  pages_StatusPage_049: "可用率",
  pages_StatusPage_050: "无数据",
  pages_StatusPage_051: "时间未知",
  pages_StatusPage_052: "正常可用",
  pages_StatusPage_053: "少量排队",
  pages_StatusPage_054: "队列拥堵",
  pages_StatusPage_055: "不可用",
  pages_StatusPage_056: "调查中",
  pages_StatusPage_057: "已确认",
  pages_StatusPage_058: "监控中",
  pages_StatusPage_059: "已解决",
  pages_StatusPage_060: "轻微影响",
  pages_StatusPage_061: "重大影响",
  pages_StatusPage_062: "严重影响",
  // Shared status labels
  serviceStatus_available: "运行正常",
  serviceStatus_busy: "运行正常，队列有少量等待",
  serviceStatus_congested: "队列拥堵",
  serviceStatus_unavailable: "暂不可用",
  serviceStatus_component_available: "正常",
  serviceStatus_component_busy: "少量排队",
  serviceStatus_component_congested: "排队较多",
  serviceStatus_component_unavailable: "不可用",
  // src/pages/admin/optimization/QueueMonitorPanel.tsx
  pages_AdminQueueStatus_001: "状态与成本输入",
  pages_AdminQueueStatus_002: "实时状态",
  pages_AdminQueueStatus_003: "用于成本估算的当前并发输入",
  pages_AdminQueueStatus_004: "计费中并发",
  pages_AdminQueueStatus_005: "配置并发",
  pages_AdminQueueStatus_006: "空闲并发",
  pages_AdminQueueStatus_007: "实时利用率",
  pages_AdminQueueStatus_008: "金额计算请结合部署单价与计费时长；本页只提供实时并发输入，不假设单价。",
  pages_AdminQueueStatus_009: "服务不可用时，实时并发输入按 0 处理。",
  pages_AdminQueueStatus_010: "排队阈值：少于 5 个为绿色，达到 5 个为黄色。",
  pages_AdminQueueStatus_013: "当前运行任务占用的并发槽",
  pages_AdminQueueStatus_014: "活跃 Worker 注册的并发容量",
  pages_AdminQueueStatus_015: "可用于成本折算的空闲槽",
  pages_AdminQueueStatus_016: "运行并发 / 配置并发",
} as const
