export const statusCopy = {
  // src/pages/StatusPage.tsx
  pages_StatusPage_001: "MaaTool 官方",
  pages_StatusPage_002: "服务状态",
  pages_StatusPage_003: "实时查看网站与排班计算服务的运行状态和可用性。",
  pages_StatusPage_004: "返回首页",
  pages_StatusPage_005: "进入工作台",
  pages_StatusPage_006: "最近更新",
  pages_StatusPage_007: "自动刷新",
  pages_StatusPage_008: "服务组件",
  pages_StatusPage_009: "排班优化计算",
  pages_StatusPage_010: "提供排班、优化建议与场景分析服务。",
  pages_StatusPage_015: "状态判定",
  pages_StatusPage_016: "服务资源充足，可正常处理请求",
  pages_StatusPage_017: "服务保持可用，处理能力略有下降",
  pages_StatusPage_018: "服务保持可用，处理时间可能延长",
  pages_StatusPage_019: "服务暂时不可用",
  pages_StatusPage_021: "状态暂时无法获取",
  pages_StatusPage_022: "无法连接到状态接口，请稍后重试。",
  pages_StatusPage_023: "重新检查",
  pages_StatusPage_024: "正在读取服务状态…",
  pages_StatusPage_025: "深绿色",
  pages_StatusPage_026: "绿色",
  pages_StatusPage_027: "黄色",
  pages_StatusPage_028: "红色",
  pages_StatusPage_029: "个",
  pages_StatusPage_030: "个并发槽",
  pages_StatusPage_031: "状态根据实时 Worker 注册表和优化队列快照计算，帮助你快速了解服务可用性。",
  pages_StatusPage_032: "当前服务运行正常。",
  pages_StatusPage_033: "服务运行正常，可用性略有下降。",
  pages_StatusPage_034: "服务当前繁忙，处理时间可能延长。",
  pages_StatusPage_035: "服务暂时不可用，请稍后重试。",
  pages_StatusPage_036: "历史可用性",
  pages_StatusPage_037: "过去 30 天",
  pages_StatusPage_038: "每个方格代表一个小时，并按 Asia/Shanghai 展示。",
  pages_StatusPage_039: "已采集",
  pages_StatusPage_040: "个样本。",
  pages_StatusPage_041: "部分历史数据暂不可用，灰色方格表示没有采样。",
  pages_StatusPage_042: "状态图例",
  pages_StatusPage_043: "过去 30 天每小时状态",
  pages_StatusPage_044: "事件时间线",
  pages_StatusPage_045: "服务事件",
  pages_StatusPage_046: "过去 30 天没有公开事件。",
  pages_StatusPage_047: "开始于",
  pages_StatusPage_048: "样本",
  pages_StatusPage_049: "可用率",
  pages_StatusPage_050: "无数据",
  pages_StatusPage_051: "时间未知",
  pages_StatusPage_052: "正常可用",
  pages_StatusPage_053: "可用，处理稍慢",
  pages_StatusPage_054: "服务繁忙",
  pages_StatusPage_055: "不可用",
  pages_StatusPage_056: "调查中",
  pages_StatusPage_057: "已确认",
  pages_StatusPage_058: "监控中",
  pages_StatusPage_059: "已解决",
  pages_StatusPage_060: "轻微影响",
  pages_StatusPage_061: "重大影响",
  pages_StatusPage_062: "严重影响",
  pages_AdminServiceStatusHistory_001: "用于评估服务历史的并发、利用率与排队峰值。",
  pages_AdminEcsCost_001: "ECS 按量成本计划",
  pages_AdminEcsCost_002: "按 Worker ECS 实例小时估算费用，并根据历史负载生成峰谷启停建议。",
  pages_AdminEcsCost_003: "计费模型",
  pages_AdminEcsCost_004: "ECS 按量计费",
  pages_AdminEcsCost_005: "每实例每小时单价（元）",
  pages_AdminEcsCost_006: "未填写单价",
  pages_AdminEcsCost_007: "启用峰谷启停计划",
  pages_AdminEcsCost_008: "费用按 Worker ECS 实例小时核算，峰谷计划用于设定每日实例数。",
  pages_AdminEcsCost_009: "低谷常态实例数",
  pages_AdminEcsCost_010: "低谷时段持续运行的 Worker ECS 实例数；填写 0 表示默认关闭。",
  pages_AdminEcsCost_011: "峰时段计划",
  pages_AdminEcsCost_012: "开始",
  pages_AdminEcsCost_013: "结束",
  pages_AdminEcsCost_014: "实例数",
  pages_AdminEcsCost_015: "添加时段",
  pages_AdminEcsCost_016: "移除",
  pages_AdminEcsCost_017: "自动启停建议",
  pages_AdminEcsCost_018: "基于最近 30 天按上海时区聚合的 Worker 实例数、利用率和拥堵样本动态生成。",
  pages_AdminEcsCost_019: "采用推荐计划",
  pages_AdminEcsCost_020: "历史样本",
  pages_AdminEcsCost_021: "推荐低谷实例数",
  pages_AdminEcsCost_022: "推荐峰时段",
  pages_AdminEcsCost_023: "推荐依据",
  pages_AdminEcsCost_024: "观测充分",
  pages_AdminEcsCost_025: "样本较少",
  pages_AdminEcsCost_026: "暂无样本",
  pages_AdminEcsCost_027: "过去 24 小时实例小时",
  pages_AdminEcsCost_028: "过去 30 天实例小时",
  pages_AdminEcsCost_029: "计划每日实例小时",
  pages_AdminEcsCost_030: "计划每月实例小时",
  pages_AdminEcsCost_031: "预计每日费用",
  pages_AdminEcsCost_032: "预计每月费用",
  pages_AdminEcsCost_033: "保存成本计划",
  pages_AdminEcsCost_034: "保存中…",
  pages_AdminEcsCost_035: "成本计划已保存",
  pages_AdminEcsCost_036: "元",
  pages_AdminEcsCost_037: "小时",
  pages_AdminEcsCost_038: "全天持续运行",
  pages_AdminEcsCost_039: "历史样本不足，沿用当前常态实例数。",
  pages_AdminEcsCost_040: (hours: number) => `按上海时区分析了 ${hours} 个小时段的历史样本。`,
  pages_AdminEcsCost_041: "拥堵或排队峰值出现的时段会提高推荐实例数。",
  pages_AdminEcsCost_042: "历史负载会生成峰谷实例数方案，确认后可作为后续 ECS 调度计划。",
  pages_AdminEcsCost_043: "推荐可信度",
  pages_AdminEcsCost_044: "建议覆盖至少 12 个小时段后采用推荐计划。",
  // Shared status labels
  serviceStatus_available: "运行正常",
  serviceStatus_busy: "运行正常，处理稍慢",
  serviceStatus_congested: "服务繁忙",
  serviceStatus_unavailable: "暂不可用",
  serviceStatus_component_available: "正常",
  serviceStatus_component_busy: "可用，处理稍慢",
  serviceStatus_component_congested: "服务繁忙",
  serviceStatus_component_unavailable: "不可用",
  // src/pages/admin/optimization/QueueMonitorPanel.tsx
  pages_AdminQueueStatus_001: "实时资源状态",
  pages_AdminQueueStatus_002: "运行资源",
  pages_AdminQueueStatus_003: "ECS 成本计划使用 Worker 实例小时；当前快照用于观察服务负载。",
  pages_AdminQueueStatus_004: "运行中并发",
  pages_AdminQueueStatus_005: "并发容量",
  pages_AdminQueueStatus_006: "空闲并发",
  pages_AdminQueueStatus_007: "实时利用率",
  pages_AdminQueueStatus_008: "费用按 ECS 每实例每小时单价和启停计划估算，并发用于衡量服务负载。",
  pages_AdminQueueStatus_009: "服务不可用时，实时并发输入按 0 处理。",
  pages_AdminQueueStatus_010: "排队阈值：少于 5 个为绿色，达到 5 个为黄色。",
  pages_AdminQueueStatus_013: "当前运行任务占用的并发槽",
  pages_AdminQueueStatus_014: "活跃 Worker 注册的并发容量",
  pages_AdminQueueStatus_015: "可用于成本折算的空闲槽",
  pages_AdminQueueStatus_016: "运行并发 / 配置并发",
} as const
