export const v2Copy = {
  brand: 'MaaTool',
  brandDescription: '基建排班工具',
  testVersion: 'V2',
  testEntry: '进入 V2 工作台',
  testEntryDescription: '在第二代工作台管理游戏账号、生成排班并使用工具。',
  legacyEntry: '旧版入口（V1）',
  generation: '生成与计算',
  generationDescription: '选择生成选项，查看配置变化并生成或更新排班。',
  plansDescription: '保存常用配置、查看历史排班，并管理方案归档。',
  lab: '方案对比',
  tools: '实用工具',
  toolsDescription: '手动安排基建、规划干员培养，或计算仓库价值。',
  addAccount: '添加账号',
  addAccountDescription: '绑定森空岛添加游戏账号，也可兑换已有 CDK。',
  settings: '账号设置',
  settingsDescription: '管理密码、通知、动画偏好和账号数据。',
  announcements: '查看公告',
  profilesDescription: '切换游戏账号，编辑档案名称与备注，或添加新账号。',
  inventoryDescription: '查看和使用道具，管理档案容量与导出体验。',
  signInRequired: '登录后即可使用此功能。',
  profileRequired: '先添加游戏账号并导入干员，再使用此功能。',
  featureUnavailable: '此功能暂时关闭，请稍后再试。',
  manualTab: '手动调整',
  trainingTab: '培养建议',
  backToTools: '返回工具列表',
  refreshSkland: '同步森空岛数据',
  discardManual: '手动排班有修改尚未保存，是否放弃修改并继续？',
  workspace: '工作台',
  infrastructure: '基建排班',
  navigation: '工作台导航',
  overview: '排班总览',
  history: '历史方案',
  configuration: '配置与数据',
  operators: '干员管理',
  facilities: '基建配置',
  personal: '个人中心',
  account: '账号与档案',
  helpAction: '使用指南',
  contents: '本页内容',
  menu: '展开导航',
  close: '关闭',
  updates: '更新日志',
  guest: '访客博士',
  login: '登录账号',
  sample: '示例模式',
  sampleSource: '内置示例数据',
  ownSource: '当前游戏账号档案',
  title: '排班总览',
  resultReady: '当前方案',
  resultDescription: '查看干员排班和预计产出，按需调整配置并生成新方案。',
  configure: '调整配置',
  regenerate: '重新排班',
  generating: '正在排班',
  stopSchedule: '停止排班',
  stopping: '正在停止…',
  export: '导出',
  exportTitle: '导出排班',
  exportDescription: '选择执行文件、排班图片或计算数据。导出对应当前打开的排班结果。',
  exportMaa: '下载 MAA JSON',
  maaFile: 'MAA 执行文件',
  maaFileDescription: '导入 MAA，让助手按当前方案自动换班。',
  scheduleImages: '排班图片',
  scheduleImagesDescription: '保存干员与设施安排，方便分享或对照换班。',
  imageShift: (name: string) => `当前选择：${name}`,
  calculationFile: '完整计算数据',
  sampleFile: '示例数据',
  sampleExport: '下载示例 JSON',
  exported: '已下载示例数据。生成个人排班后，可从「导出」下载 MAA 执行文件。',
  resultTabs: '结果视图',
  scheduleTab: '排班安排',
  analysisTab: '收益分析',
  productionDetails: '产出汇总与库存',
  previewAnalysis: '免费预览可查看总体产出。各站点的产量明细与等效理智计算需要高级版权益。',
  comparePlans: '比较价格与权益',
  result: '排班安排',
  shiftTabs: '选择班次',
  shift: (index: number) => `第 ${index} 班`,
  shifts: (count: number) => `${count} 班轮换`,
  shiftHours: (hours: string) => `每班 ${hours} 小时`,
  assigned: (count: number) => `${count} 位干员在岗`,
  duration: '换班间隔',
  grid: '卡片视图',
  list: '列表视图',
  room: '设施',
  team: '在岗干员',
  efficiency: '生产效率',
  equivalentEfficiency: '等效理智效率',
  expectedFullOrders: '预计满单 ',
  startMood: '初始心情',
  endMood: '结束心情',
  moodUnavailable: '未提供',
  skillsUnavailable: '暂无基建技能信息',
  schedule: '排班方案',
  lmd: '预计龙门币',
  exp: '预计作战记录',
  orundum: '预计合成玉',
  totalEfficiency: '总生产效率',
  sanity: '等效理智',
  sanityUnit: '理智 / 天',
  sustainablePulls: '可持续抽数',
  pullsPer30Days: '抽 / 30 天',
  sustainablePullsHint: (amount: string) => `按当前理智预算与基建产能估算 · 每日可产出 ${amount} 合成玉`,
  shortTermOrundumHint: '按当前库存支持的短期产量估算',
  inventoryBurstHint: (days: string) => `当前较高产量预计可维持 ${days} 天`,
  sustainableOrundumUnavailable: '暂无可持续产量数据',
  orundumInputs: '搓玉投入与库存',
  daily: '/ 天',
  expUnit: '经验 / 天',
  efficiencyHint: '按当前排班方案汇总',
  sanityHint: '用于比较不同产出的理智价值',
  dailyOutput: '每日预计产出',
  outputSubtitle: '每日产出按完整排班周期折算为 24 小时。',
  stationOutput: '各站点每日产出',
  stationOutputNote: '产量已按排班周期折算为每日，包含单独列出的无人机增产。贸易站订单量和收益为预估值。',
  noStationOutput: '当前结果没有站点产量明细。重新排班后可查看各站点产出；总体收益仍可查看下方计算。',
  shiftLabel: '班次 / 来源',
  estimatedAmount: '预计产量 / 天',
  consumption: '消耗 / 天',
  sanityContribution: '净等效理智 / 天',
  sanityCalculation: '等效理智计算',
  sanityCalculationNote: '产出价值减去赤金、源石碎片等消耗的价值，避免重复计算。折算用于方案比较，不代表每天可领取的理智。',
  sanityFormula: '净等效理智 = 制造产出价值 + 贸易产出价值 − 消耗价值',
  orundumCapacity: '可持续产量依据',
  orundumCapacityNote: '可持续产量取理智预算、制造站和贸易站产能中的最低值。每 2 个固源岩与 1,600 龙门币可制造 1 个源石碎片，每 2 个碎片可换取 20 合成玉。库存可临时提高短期产量，每日材料和龙门币消耗按可持续产量估算。',
  dailySanityBudget: '每日理智预算',
  monthlyCardSanity: '月卡理智加成',
  totalSanityBudget: '每日理智总预算',
  dailyOrirockSupply: '每日固源岩供应',
  rockLimitedOrundum: '理智预算支持的合成玉产量',
  factoryOrundumCapacity: '制造站支持的合成玉产量',
  tradeOrundumCapacity: '贸易站合成玉产能',
  sustainableOrundum: '可持续合成玉产量',
  shortTermOrundum: '短期合成玉产量',
  inventoryDepletion: '库存预计耗尽时间',
  goldNetChange: '赤金净变动',
  intermediateInventory: '中间产物库存',
  daysUnit: '天',
  orirockUnit: '个 / 天',
  orundumUnit: '合成玉 / 天',
  dailyShardConsumption: '每日源石碎片用量',
  calculationItem: '计算项目',
  calculationBasis: '计算依据',
  orirockCost: '每日固源岩消耗',
  shardLmdCost: '每日龙门币消耗',
  conversion: '每单位理智价值',
  outputValue: '产出价值',
  consumptionValue: '消耗价值',
  capacityLimited: '受容量限制',
  currentConfig: '当前配置',
  edit: '编辑',
  layout: '基建布局',
  production: '生产目标',
  productionValue: '龙门币 + 作战记录',
  mode: '排班模式',
  drones: '无人机',
  automatic: '自动分配',
  manual: '手动指定',
  disabled: '未启用',
  operatorData: '干员数据',
  owned: (count: number) => `已拥有 ${count} 位干员`,
  manage: '管理干员',
  statusReady: '示例可浏览',
  sampleHint: '登录并导入自己的干员后，可生成个人排班。',
  configChanged: '配置已修改，当前仍是上次结果。点击「重新排班」应用修改。',
  demoConfigChanged: '示例配置已修改，排班保持原样。登录后可生成个人方案。',
  dataPending: '先导入干员并调整基建配置，再点击「重新排班」生成个人方案。',
  loading: '正在加载排班…',
  loadingResult: '正在读取最近一次排班…',
  resultLoadFailed: '最近一次排班读取失败，请重试。',
  retry: '重新读取',
  noPersonalResult: '当前展示示例，尚未生成个人排班',
  sampleNotice: '示例数据可用于了解界面与文件格式，个人收益请查看自己生成的排班方案。',
  estimateNotice: '所有产出均为测算值，实际收益受干员心情、订单与执行方式影响。',
  terms: '服务条款',
  privacy: '隐私政策',
  configDescription: '修改会自动保存，点击「重新排班」后更新结果。',
  demoConfigDescription: '可调整示例配置。登录并导入自己的干员后，可生成个人排班。',
  done: '完成调整',
  searchOperators: '搜索干员名称',
  noOperators: '没有找到匹配的干员。',
  operatorDescription: '获得或培养干员后，请重新上传 MAA 干员 JSON，或从森空岛同步。',
  sampleOperatorDescription: '当前为示例干员。可上传 MAA 干员 JSON，登录后也可从森空岛同步。',
  importOperators: '导入或同步干员',
  accountDescription: '登录后可查看已有档案和最近一次排班。',
  loginUnavailable: '账号服务暂不可用，可继续浏览示例，稍后重试登录。',
  loginRetry: '重试账号连接',
  profiles: '我的游戏账号档案',
  manageProfiles: '管理档案',
  profileSearch: '搜索账号或备注',
  currentAccount: '当前账号',
  preferenceDescription: '调整动画效果和调试信息。',
  activeProfiles: '使用中的档案',
  totalProfiles: '全部档案',
  noMatches: '没有找到匹配的内容。',
  updated: '最近更新',
  validity: '有效期',
  prepare: '准备数据与配置',
  execute: '生成排班',
  savedConfigurations: '配置库',
  savedResults: '排班记录',
  searchRecords: '搜索排班记录',
  selectRecord: '选择一条记录',
  selectRecordHint: '查看记录信息，应用配置或导出排班。',
  inventoryItems: '道具',
  inventoryActivity: '获取与使用记录',
  toolSource: '数据来源',
  toolParameters: '规划条件',
  toolOutcome: '规划结果',
  readAll: '全部公告',
  readUnread: '未读公告',
  selectAnnouncement: '选择一则公告',
  planChoice: '选择使用期限',
  reviewEntitlements: '查看方案权益',
  selectedPlan: '已选方案',
  serviceHistory: '过去 7 天',
  setupAccount: '选择游戏账号',
  setupLayout: '设置基建与班次',
  setupSchedule: '开始编排',
  logout: '退出登录',
  noProfiles: '还没有游戏账号档案，点击「添加账号」开始。',
  sampleHistory: '示例方案',
  roomDescription: '查看该设施的干员安排与计算依据。',
  level: '设施等级',
  maxLevel: '满级',
  unknownLevel: '等级未知',
  product: '当前产物',
  roomDetails: '计算依据',
  support: '辅助设施',
  productionRooms: '生产设施',
  controlAndPower: '中枢与供能',
  supportAndDormitories: '辅助设施与宿舍',
  resting: '宿舍安排',
  expandRooms: '展开设施',
  compactRooms: '紧凑显示',
  exportUnavailable: '游戏内轮换模式不生成 MAA JSON。',
  chooseProfile: '切换档案前请等待当前排班完成。',
  saveFailed: '配置保存失败，请重试后再生成排班。',
  elite: (elite: number) => `精英${elite}`,
  operatorLevel: (level?: number | string) => level === undefined ? '等级未知' : `Lv.${level}`,
  ownedLabel: '已拥有',
  notOwnedLabel: '未拥有',
  uploadMaa: '上传 MAA 干员 JSON',
  bindSkland: '从森空岛导入',
  importSuccess: '干员数据已导入。点击「重新排班」生成新的方案。',
  sampleImportSuccess: '干员数据已导入，示例排班保持原样。登录后可生成个人方案。',
  uploadFailed: '文件读取失败，请检查干员 JSON 格式。',
  sampleOperators: {
    silverash: '银灰', degenbrecher: '锏', gnosis: '灵知', proviso: '但书',
    tequila: '龙舌兰', shamare: '巫恋', exusiai: '能天使', texas: '德克萨斯',
    lappland: '拉普兰德', arene: '芳汀', steward: '史都华德', midnight: '月见夜',
    dorothy: '多萝西', silence: '赫默', ptilopsis: '白面鸮', vermeil: '红云',
    scene: '稀音', ceobe: '刻俄柏', gravel: '砾', spot: '斑点', haze: '夜烟',
    weedy: '温蒂', passenger: '异客', eunectes: '森蚺', frostleaf: '霜叶',
    vigna: '红豆', shirayuki: '白雪', conviction: '断罪者', castle: 'Castle-3',
    wildmane: '野鬃', amiya: '阿米娅', kaltsit: '凯尔希', mlynar: '玛恩纳',
    siege: '推进之王', chen: '陈', greyy: '格雷伊', liskarm: '雷蛇',
    ifrit: '伊芙利特', mostima: '莫斯提马', indigo: '深靛', lumen: '流明',
    fiammetta: '菲亚梅塔',
  },
} as const
