export const v2Copy = {
  brand: 'MaaTool',
  brandDescription: '基建调度工作台',
  testVersion: 'V2 测试版',
  testEntry: '体验 V2 测试版',
  backToV1: '返回 V1',
  workspace: '工作台',
  infrastructure: '基建排班',
  navigation: '工作台导航',
  overview: '排班总览',
  history: '历史方案',
  configuration: '配置与数据',
  operators: '干员管理',
  facilities: '基建配置',
  preferences: '排班偏好',
  personal: '个人中心',
  account: '账号与档案',
  cdk: 'CDK 与权益',
  help: '需要一点帮助？',
  helpDescription: '从导入干员到使用排班，快速找到答案。',
  helpAction: '查看使用指南',
  version: 'v2 测试版 · 让基建更简单',
  menu: '展开导航',
  close: '关闭',
  updates: '更新日志',
  guest: '访客博士',
  login: '登录账号',
  sample: '示例模式',
  sampleProfile: '罗德岛 · 示例档案',
  sampleSource: '内置示例数据',
  ownSource: '当前游戏账号档案',
  eyebrow: 'RHODES ISLAND / BASE OPERATIONS',
  title: '基建排班，一目了然。',
  subtitle: '你的干员各就各位，把时间留给下一场作战。',
  resultReady: '排班方案已就绪',
  resultDescription: '先看结果，按需调整。修改配置后，点击重新排班即可。',
  configure: '调整配置',
  regenerate: '重新排班',
  generating: '正在排班',
  export: '导出 MAA',
  sampleExport: '下载示例 JSON',
  exported: '示例 JSON 已下载，可用于查看示例排班的数据结构。执行个人排班请使用「导出 MAA」。',
  resultTabs: '结果视图',
  summaryTab: '总览',
  detailsTab: '排班详情',
  analysisTab: '收益分析',
  result: '排班安排',
  shiftTabs: '选择班次',
  shift: (index: number) => `第 ${index} 班`,
  shifts: (count: number) => `${count} 班轮换`,
  shiftHours: (hours: string) => `${hours} 小时 / 班`,
  assigned: (count: number) => `${count} 位干员在岗`,
  duration: '换班间隔',
  grid: '卡片视图',
  list: '列表视图',
  room: '设施',
  team: '在岗干员',
  efficiency: '生产效率',
  schedule: '排班方案',
  lmd: '预计龙门币',
  exp: '预计作战记录',
  totalEfficiency: '总生产效率',
  sanity: '等效理智',
  daily: '/ 天',
  expUnit: '经验 / 天',
  efficiencyHint: '按当前排班方案汇总',
  sanityHint: '统一产出价值的参考口径',
  dailyOutput: '每日预计产出',
  outputSubtitle: '按完整排班周期折算至 24 小时',
  outputChart: '龙门币累计产出',
  chartDescription: '按预计日产出均匀折算，非游戏实测曲线。',
  currentConfig: '当前配置',
  edit: '编辑',
  layout: '基建布局',
  production: '生产目标',
  productionValue: '龙门币 + 作战记录',
  mode: '排班模式',
  drones: '无人机',
  automatic: '自动分配',
  manual: '手动指定',
  disabled: '未启用',
  operatorData: '干员数据',
  owned: (count: number) => `已拥有 ${count} 位干员`,
  manage: '管理干员',
  statusReady: '示例可浏览',
  sampleHint: '当前展示内置示例方案。登录并导入自己的干员后，可生成个人排班。',
  configChanged: '配置已变更。当前仍展示上次结果，点击「重新排班」应用修改。',
  demoConfigChanged: '已调整示例配置。示例排班保持原样，登录后可用新配置生成个人方案。',
  dataPending: '还没有个人排班。先在选项中准备干员与基建配置，再生成第一份方案。',
  loadingResult: '正在读取最近一次排班…',
  resultLoadFailed: '最近一次排班读取失败，请重试。',
  retry: '重新读取',
  noPersonalResult: '当前展示示例，尚未生成个人排班',
  sampleNotice: '示例数据仅用于了解界面与文件格式，不代表你的游戏账号收益。',
  estimateNotice: '所有产出均为测算值，实际收益受干员心情、订单与执行方式影响。',
  footer: 'MaaTool · 为博士留出更多时间',
  terms: '服务条款',
  privacy: '隐私政策',
  drawerDescription: '按需调整选项，排班结果始终留在工作台。',
  configDescription: '配置单独保存。需要更新结果时，再点击「重新排班」。',
  demoConfigDescription: '可以预览配置选项。个人排班需要登录并导入自己的干员。',
  done: '完成调整',
  searchOperators: '搜索干员名称',
  noOperators: '没有找到匹配的干员。',
  importOperators: '导入或同步干员',
  importDescription: '使用现有导入流程读取森空岛或 MAA 数据，完成后返回工作台。',
  accountDescription: '登录后读取已有档案和最近一次排班，无需重新完成准备流程。',
  loginUnavailable: '账号服务暂不可用，你仍可以浏览示例。服务恢复后可重试登录。',
  loginRetry: '重试账号连接',
  profiles: '我的游戏账号档案',
  manageProfiles: '管理档案',
  logout: '退出登录',
  noProfiles: '还没有游戏账号档案。可在档案管理中添加。',
  sampleHistory: '示例方案',
  historyDescription: '选择已保存的方案，直接回到结果查看。',
  noHistory: '还没有保存的排班方案。',
  cdkDescription: 'CDK 与档案权益在需要时管理，不影响浏览示例排班。',
  manageCdk: '兑换 CDK / 管理权益',
  roomDescription: '查看该设施的干员安排与计算依据。',
  level: '设施等级',
  product: '当前产物',
  roomDetails: '计算依据',
  support: '辅助设施',
  resting: '宿舍安排',
  allRooms: '全部设施与干员安排',
  exportUnavailable: '游戏内轮换模式不生成 MAA JSON。',
  chooseProfile: '切换档案前请等待当前排班完成。',
  loadingConfig: '正在加载配置选项…',
  saveFailed: '配置保存失败，请重试后再生成排班。',
  elite: '精英化',
  ownedLabel: '已拥有',
  saveOperatorsFailed: '干员信息保存失败，请重试。',
  uploadMaa: '上传 MAA 干员 JSON',
  bindSkland: '从森空岛导入',
  importSuccess: '干员数据已导入。点击「重新排班」生成新的方案。',
  uploadFailed: '文件读取失败，请检查干员 JSON 格式。',
  sampleOperators: {
    silverash: '银灰', degenbrecher: '锏', gnosis: '灵知', proviso: '但书',
    tequila: '龙舌兰', shamare: '巫恋', exusiai: '能天使', texas: '德克萨斯',
    lappland: '拉普兰德', arene: '芳汀', steward: '史都华德', midnight: '月见夜',
    dorothy: '多萝西', silence: '赫默', ptilopsis: '白面鸮', vermeil: '红云',
    scene: '稀音', ceobe: '刻俄柏', gravel: '砾', spot: '斑点', haze: '夜烟',
    weedy: '温蒂', passenger: '异客', eunectes: '森蚺', frostleaf: '霜叶',
    vigna: '红豆', shirayuki: '白雪', conviction: '断罪者', castle: 'Castle-3',
    wildmane: '野鬃', amiya: '阿米娅', kaltsit: '凯尔希', mlynar: '玛恩纳',
    siege: '推进之王', chen: '陈', greyy: '格雷伊', liskarm: '雷蛇',
    ifrit: '伊芙利特', mostima: '莫斯提马', indigo: '深靛', lumen: '流明',
    fiammetta: '菲亚梅塔',
  },
} as const
