import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(root, 'netlify/functions/efficiency-data.json')
const targetPath = resolve(root, 'netlify/functions/data.ts')

const source = await readFile(sourcePath, 'utf8')
const data = JSON.parse(source.replace(/^\uFEFF/, ''))
const output = [
  '// Auto-generated from efficiency-data.json',
  '// Do not edit this file directly. Update efficiency-data.json and run npm run generate:data.',
  `export const EFFICIENCY_DATA: Record<string, unknown> = ${JSON.stringify(data)};`,
  '',
].join('\n')

await writeFile(targetPath, output, 'utf8')
