import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(root, 'netlify/functions/efficiency-data.json')
const targetPath = resolve(root, 'netlify/functions/data.ts')
const buildMetaPath = resolve(root, 'src/lib/build-meta.ts')
const packagePath = resolve(root, 'package.json')
const LINE_ENDING = '\r\n'

const source = await readFile(sourcePath, 'utf8')
const data = JSON.parse(source.replace(/^\uFEFF/, ''))
const packageJson = JSON.parse(await readFile(packagePath, 'utf8'))
const sourceHash = createHash('sha256').update(source).digest('hex')
const shortSha = getShortSha()
const baseVersion = String(packageJson.version || '0.0.0')
const semanticVersion = buildSemanticVersion(baseVersion)
const buildId = process.env.GITHUB_RUN_NUMBER || process.env.DEPLOY_ID || process.env.BUILD_ID || 'local'
const defaultBuildVersion = shortSha
  ? `${semanticVersion}+${buildId}.${shortSha}`
  : buildId === 'local'
    ? semanticVersion
    : `${semanticVersion}+${buildId}`
const dataVersion = process.env.DATA_VERSION || `data.${sourceHash.slice(0, 12)}`
const sourceSummary = buildSourceSummary(data, sourceHash)
const generatedAt = process.env.GENERATED_AT ||
  await readExistingGeneratedAt(dataVersion, sourceSummary) ||
  new Date().toISOString()
const appBuildMeta = {
  frontend_version: process.env.FRONTEND_VERSION || process.env.APP_VERSION || defaultBuildVersion,
  backend_version: process.env.BACKEND_VERSION || process.env.APP_VERSION || defaultBuildVersion,
  data_version: dataVersion,
  generated_at: generatedAt,
  source_summary: sourceSummary,
  git_sha: process.env.GIT_SHA || process.env.GITHUB_SHA || process.env.COMMIT_REF || null,
  build_context: process.env.BUILD_CONTEXT || process.env.GITHUB_EVENT_NAME || process.env.CONTEXT || 'local',
}
const dataMetadata = {
  data_version: appBuildMeta.data_version,
  generated_at: appBuildMeta.generated_at,
  source_summary: appBuildMeta.source_summary,
}
const output = [
  '// Auto-generated from efficiency-data.json',
  '// Do not edit this file directly. Update efficiency-data.json and run npm run generate:data.',
  `export const EFFICIENCY_DATA_METADATA = ${JSON.stringify(dataMetadata)} as const;`,
  `export const EFFICIENCY_DATA: Record<string, unknown> = ${JSON.stringify(data)};`,
  '',
].join(LINE_ENDING)

await writeFile(targetPath, output, 'utf8')

const buildMetaOutput = [
  '// Auto-generated by scripts/generate-data.mjs',
  '// Do not edit this file directly.',
  `export const APP_BUILD_META = ${JSON.stringify(appBuildMeta, null, 2).replace(/\n/g, LINE_ENDING)} as const;`,
  '',
  'export type AppBuildMeta = typeof APP_BUILD_META;',
  '',
].join(LINE_ENDING)

await writeFile(buildMetaPath, buildMetaOutput, 'utf8')

function getShortSha() {
  const sha = process.env.GIT_SHA || process.env.GITHUB_SHA || process.env.COMMIT_REF
  return sha ? sha.slice(0, 7) : ''
}

function buildSemanticVersion(baseVersion) {
  const match = baseVersion.match(/^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/)
  if (!match) return baseVersion

  const [, major, minor, patch] = match
  const autoPatch = getAutoPatchNumber()
  return `${major}.${minor}.${autoPatch ?? patch}`
}

function getAutoPatchNumber() {
  const explicitPatch = readPositiveInteger(process.env.VERSION_PATCH)
  if (explicitPatch !== null) return explicitPatch

  const buildPatch = readPositiveInteger(process.env.BUILD_NUMBER) ??
    readPositiveInteger(process.env.GITHUB_RUN_NUMBER)
  if (buildPatch !== null) return buildPatch

  try {
    const output = execFileSync('git', ['rev-list', '--count', 'HEAD'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
    return readPositiveInteger(output.trim())
  } catch {
    return null
  }
}

function readPositiveInteger(value) {
  if (value === undefined || value === null || value === '') return null
  const number = Number.parseInt(String(value), 10)
  return Number.isInteger(number) && number >= 0 ? number : null
}

async function readExistingGeneratedAt(dataVersion, sourceSummary) {
  try {
    const content = await readFile(buildMetaPath, 'utf8')
    const existingDataVersion = readJsonStringField(content, 'data_version')
    const existingSourceSummary = readJsonStringField(content, 'source_summary')
    const existingGeneratedAt = readJsonStringField(content, 'generated_at')
    if (
      existingDataVersion === dataVersion &&
      existingSourceSummary === sourceSummary &&
      existingGeneratedAt
    ) {
      return existingGeneratedAt
    }
  } catch {
    // First generation, or a broken generated file, should fall back to a fresh timestamp.
  }
  return null
}

function readJsonStringField(content, fieldName) {
  const fieldPattern = new RegExp(`"${escapeRegExp(fieldName)}"\\s*:\\s*("(?:\\\\.|[^"\\\\])*")`)
  const match = content.match(fieldPattern)
  if (!match) return null
  return JSON.parse(match[1])
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function buildSourceSummary(rawData, hash) {
  const workplaces = rawData.workplaces ?? {}
  const tradingRules = rawData.combination_rules?.trading_station ?? {}
  const manufacturingRules = rawData.combination_rules?.manufacturing_station ?? {}
  const controlRules = rawData.control_center_rules ?? []
  const workplaceCount = Object.values(workplaces).reduce((count, value) => {
    if (Array.isArray(value)) return count + value.length
    return count + (value ? 1 : 0)
  }, 0)

  return [
    'source=netlify/functions/efficiency-data.json',
    `sha256=${hash.slice(0, 12)}`,
    `workplaces=${workplaceCount}`,
    `trading_rule_groups=${Object.keys(tradingRules).length}`,
    `manufacturing_rule_groups=${Object.keys(manufacturingRules).length}`,
    `control_center_rules=${Array.isArray(controlRules) ? controlRules.length : 0}`,
  ].join('; ')
}
