#!/usr/bin/env python3
"""Generate minimal square Xianyu listing covers for points recharge tiers.

The image model only creates a text-free background. Pillow overlays the exact
points amount and bonus label so listing thumbnails never contain AI-mangled
numbers or Chinese text.

The script never stores credentials. Set KRILL_AI_API_KEY in the environment
before running a non-dry command. Existing assets are skipped unless --force is
supplied. Public tiers are generated by default; use --include-test or --only 1
to include the internal 1 yuan test tier.
"""

from __future__ import annotations

import argparse
import base64
import os
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from openai import OpenAI
from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageStat

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "public" / "assets" / "points-listing-covers"
DEFAULT_BASE_URL = "https://api.krill-ai.net/v1"
DEFAULT_MODEL = "gpt-image-2"
FINAL_SIZE = 1024


@dataclass(frozen=True)
class ListingTier:
    price_yuan: int
    base_points: int
    bonus_points: int
    accent_description: str
    public: bool = True

    @property
    def code(self) -> str:
        return str(self.price_yuan)

    @property
    def total_points(self) -> int:
        return self.base_points + self.bonus_points

    @property
    def filename(self) -> str:
        return f"points-tier-{self.price_yuan}-yuan.png"


LISTING_TIERS = (
    ListingTier(
        price_yuan=1,
        base_points=100,
        bonus_points=0,
        accent_description="克制的藏青与银蓝配色，少量冷青色光点",
        public=False,
    ),
    ListingTier(
        price_yuan=5,
        base_points=500,
        bonus_points=0,
        accent_description="清爽的深蓝与青蓝渐变，少量明亮青色光点",
    ),
    ListingTier(
        price_yuan=10,
        base_points=1_000,
        bonus_points=0,
        accent_description="深皇家蓝与高亮青蓝渐变，边缘带少量柔和蓝色辉光",
    ),
    ListingTier(
        price_yuan=20,
        base_points=2_000,
        bonus_points=100,
        accent_description="深皇家蓝、青蓝与少量暖金色点缀，体现轻量升级感",
    ),
    ListingTier(
        price_yuan=50,
        base_points=5_000,
        bonus_points=500,
        accent_description="浓郁藏青与高亮青蓝渐变，使用更明确但克制的暖金色边缘点缀",
    ),
    ListingTier(
        price_yuan=100,
        base_points=10_000,
        bonus_points=1_500,
        accent_description="高级深蓝与暖金色渐变，辅以少量高亮青蓝光点，精致但不奢华",
    ),
)


COMMON_BACKGROUND_PROMPT = """
Use case: marketplace-listing-background
Asset type: square Xianyu marketplace listing cover background without text

Primary request:
为站内积分充值商品生成一张简洁、高识别度的正方形闲鱼首图背景。脚本之后会在画面中央叠加非常大的准确积分数字，因此本次只生成背景，绝对不要生成任何文字或数字。

Composition/framing:
正方形 1:1 构图，正面平视。中央约 65% 区域必须安静、简洁、低细节，给后期大字保留完整安全区；装饰集中在四角和画面边缘，不遮挡中央。使用现代科技感渐变、少量柔和光点、极简票券切角或抽象积分轨迹作为边缘装饰。移动端缩略图中仍要清晰、干净，不要复杂场景。

Style/medium:
现代数字产品售卖首图，精致的扁平化与轻微 2.5D 质感，高对比、干净、可信。使用大色块、柔和渐变和非常克制的边缘高光。不要写实，不要堆砌元素，不要强烈霓虹赛博朋克效果。

Lighting/mood:
柔和均匀的正面光照，稳定、明亮、可信。中央区域需要能够承载白色粗体文字，避免中央出现高亮白斑或密集纹理。

Text and exclusions:
绝对不要出现汉字、英文字母、数字、价格、货币符号、序列号、二维码、伪文字、品牌标志、商标或水印。不要人物、手、角色、金币堆、人民币、纸币、银行卡、现金、钱包、提现符号、购物袋、商品实物、复杂图标、密集粒子、长篇促销信息或价格表。
""".strip()


FONT_CANDIDATES = (
    ROOT / "public" / "assets" / "fonts" / "NotoSansSC-Bold.ttf",
    Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"),
    Path("/usr/share/fonts/opentype/noto/NotoSansCJKsc-Bold.otf"),
    Path("/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc"),
    Path("/mnt/c/Windows/Fonts/msyhbd.ttc"),
    Path("/mnt/c/Windows/Fonts/Dengb.ttf"),
    Path("/mnt/c/Windows/Fonts/simhei.ttf"),
    Path("/mnt/c/Windows/Fonts/NotoSansSC-VF.ttf"),
    Path("/mnt/c/Windows/Fonts/msyh.ttc"),
    Path("/System/Library/Fonts/PingFang.ttc"),
)


def build_prompt(tier: ListingTier) -> str:
    return "\n\n".join(
        (
            COMMON_BACKGROUND_PROMPT,
            f"Tier art direction:\n{tier.accent_description}。只通过色彩强弱区分档位，不得在背景中写出售价、积分或赠送数量。",
        )
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--only",
        action="append",
        choices=[tier.code for tier in LISTING_TIERS],
        metavar="YUAN",
        help="Generate only one yuan tier. Repeat to select multiple tiers.",
    )
    parser.add_argument(
        "--include-test",
        action="store_true",
        help="Include the internal 1 yuan / 100 points test tier in the default selection.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show planned tiers and output files without calling the image API.",
    )
    parser.add_argument(
        "--show-prompts",
        action="store_true",
        help="Print the text-free background prompt for each selected tier.",
    )
    parser.add_argument(
        "--force", action="store_true", help="Regenerate an existing final cover."
    )
    parser.add_argument(
        "--font",
        type=Path,
        help="Path to a bold Chinese TrueType/OpenType font. Common Noto, Microsoft YaHei, DengXian and SimHei paths are auto-detected.",
    )
    parser.add_argument(
        "--base-url",
        default=os.environ.get("KRILL_AI_BASE_URL", DEFAULT_BASE_URL),
        help="OpenAI-compatible API base URL.",
    )
    parser.add_argument(
        "--model", default=DEFAULT_MODEL, help="Image generation model."
    )
    return parser.parse_args()


def selected_tiers(
    codes: list[str] | None, include_test: bool
) -> tuple[ListingTier, ...]:
    if codes:
        requested = set(codes)
        return tuple(tier for tier in LISTING_TIERS if tier.code in requested)
    return tuple(tier for tier in LISTING_TIERS if tier.public or include_test)


def create_client(base_url: str) -> OpenAI:
    api_key = os.environ.get("KRILL_AI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "KRILL_AI_API_KEY is not set. Set it in the environment; never add it to this script or a repository file."
        )
    return OpenAI(base_url=base_url, api_key=api_key)


def decode_image(response: object) -> bytes:
    data = getattr(response, "data", None)
    if not data:
        raise RuntimeError("The image API returned no image data.")
    encoded = getattr(data[0], "b64_json", None)
    if not encoded:
        raise RuntimeError(
            "The image API did not return b64_json; this generator intentionally does not fetch untrusted image URLs."
        )
    return base64.b64decode(encoded)


def resolve_font(explicit: Path | None) -> Path:
    if explicit is not None:
        resolved = explicit.expanduser().resolve()
        if not resolved.is_file():
            raise RuntimeError(f"Chinese font was not found: {resolved}")
        return resolved
    for candidate in FONT_CANDIDATES:
        if candidate.is_file():
            return candidate
    raise RuntimeError(
        "No bold Chinese font was found. Install Noto Sans CJK or pass --font /absolute/path/to/a-CJK-font.ttf."
    )


def load_font(font_path: Path, size: int) -> ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype(str(font_path), size=size)
    except OSError as error:
        raise RuntimeError(
            f"Unable to load Chinese font {font_path}: {error}"
        ) from error


def fit_font(
    draw: ImageDraw.ImageDraw,
    text: str,
    font_path: Path,
    maximum: int,
    minimum: int,
    max_width: int,
) -> ImageFont.FreeTypeFont:
    for size in range(maximum, minimum - 1, -4):
        font = load_font(font_path, size)
        bounds = draw.textbbox((0, 0), text, font=font, stroke_width=max(2, size // 80))
        if bounds[2] - bounds[0] <= max_width:
            return font
    raise RuntimeError(f"Text does not fit the cover safe area: {text}")


def draw_centered_text(
    draw: ImageDraw.ImageDraw,
    text: str,
    font: ImageFont.FreeTypeFont,
    top: int,
    *,
    fill: tuple[int, int, int, int],
    stroke_width: int = 0,
    stroke_fill: tuple[int, int, int, int] | None = None,
) -> tuple[int, int, int, int]:
    bounds = draw.textbbox((0, 0), text, font=font, stroke_width=stroke_width)
    width = bounds[2] - bounds[0]
    height = bounds[3] - bounds[1]
    position = ((FINAL_SIZE - width) // 2 - bounds[0], top - bounds[1])
    draw.text(
        position,
        text,
        font=font,
        fill=fill,
        stroke_width=stroke_width,
        stroke_fill=stroke_fill,
    )
    return ((FINAL_SIZE - width) // 2, top, (FINAL_SIZE + width) // 2, top + height)


def render_cover(
    source: Path, destination: Path, tier: ListingTier, font_path: Path
) -> None:
    with Image.open(source) as source_image:
        background = ImageOps.fit(
            source_image.convert("RGB"),
            (FINAL_SIZE, FINAL_SIZE),
            method=Image.Resampling.LANCZOS,
            centering=(0.5, 0.5),
        ).convert("RGBA")

    overlay = Image.new("RGBA", background.size, (0, 0, 0, 0))
    overlay_draw = ImageDraw.Draw(overlay)
    overlay_draw.rounded_rectangle(
        (72, 86, FINAL_SIZE - 72, FINAL_SIZE - 86),
        radius=64,
        fill=(3, 12, 34, 118),
        outline=(145, 224, 255, 72),
        width=2,
    )
    background = Image.alpha_composite(background, overlay)
    draw = ImageDraw.Draw(background)

    number_text = str(tier.total_points)
    number_font = fit_font(
        draw, number_text, font_path, maximum=286, minimum=176, max_width=820
    )
    number_top = 238 if tier.bonus_points else 276
    number_bounds = draw_centered_text(
        draw,
        number_text,
        number_font,
        number_top,
        fill=(255, 255, 255, 255),
        stroke_width=4,
        stroke_fill=(5, 18, 45, 210),
    )

    unit_font = load_font(font_path, 92)
    unit_bounds = draw_centered_text(
        draw,
        "积分",
        unit_font,
        number_bounds[3] + 18,
        fill=(220, 247, 255, 255),
        stroke_width=2,
        stroke_fill=(5, 18, 45, 190),
    )

    if tier.bonus_points:
        bonus_text = f"含赠 {tier.bonus_points}"
        bonus_font = load_font(font_path, 44)
        bonus_bounds = draw.textbbox((0, 0), bonus_text, font=bonus_font)
        bonus_width = bonus_bounds[2] - bonus_bounds[0]
        bonus_height = bonus_bounds[3] - bonus_bounds[1]
        horizontal_padding = 34
        vertical_padding = 17
        pill_width = bonus_width + horizontal_padding * 2
        pill_height = bonus_height + vertical_padding * 2
        pill_left = (FINAL_SIZE - pill_width) // 2
        pill_top = unit_bounds[3] + 44
        draw.rounded_rectangle(
            (pill_left, pill_top, pill_left + pill_width, pill_top + pill_height),
            radius=pill_height // 2,
            fill=(226, 174, 65, 232),
            outline=(255, 237, 183, 220),
            width=2,
        )
        draw.text(
            (
                pill_left + horizontal_padding - bonus_bounds[0],
                pill_top + vertical_padding - bonus_bounds[1],
            ),
            bonus_text,
            font=bonus_font,
            fill=(20, 30, 52, 255),
        )

    footer_font = load_font(font_path, 38)
    draw_centered_text(
        draw,
        "站内积分充值",
        footer_font,
        858,
        fill=(218, 235, 244, 235),
        stroke_width=1,
        stroke_fill=(4, 16, 40, 160),
    )

    destination.parent.mkdir(parents=True, exist_ok=True)
    background.convert("RGB").save(destination, format="PNG", optimize=True)


def validate_cover(path: Path) -> dict[str, object]:
    with Image.open(path) as image:
        final = image.convert("RGB")
        if final.size != (FINAL_SIZE, FINAL_SIZE):
            raise RuntimeError(f"{path.name} has the wrong size: {final.size}")
        if image.format != "PNG":
            raise RuntimeError(f"{path.name} is not a PNG: {image.format}")
        variance = ImageStat.Stat(final).var
        if max(variance) < 50:
            raise RuntimeError(
                f"{path.name} appears blank or nearly uniform: variance={variance}"
            )
    return {
        "size": (FINAL_SIZE, FINAL_SIZE),
        "bytes": path.stat().st_size,
        "variance": tuple(round(value, 2) for value in variance),
    }


def generate_one(
    client: OpenAI, tier: ListingTier, model: str, font_path: Path, force: bool
) -> None:
    destination = OUTPUT_DIR / tier.filename
    if destination.exists() and not force:
        print(f"SKIP {tier.code} yuan: {destination.relative_to(ROOT)} already exists")
        return

    print(
        f"GENERATE {tier.code} yuan: base={tier.base_points} bonus={tier.bonus_points} "
        f"total={tier.total_points} -> {destination.relative_to(ROOT)}"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix=f".points-{tier.code}-yuan-", dir=destination.parent
    ) as temp_dir:
        response = client.images.generate(
            model=model,
            prompt=build_prompt(tier),
            size="1024x1024",
            quality="high",
        )
        temp_root = Path(temp_dir)
        source = temp_root / "background.png"
        rendered = temp_root / tier.filename
        source.write_bytes(decode_image(response))
        render_cover(source, rendered, tier, font_path)
        metadata = validate_cover(rendered)
        os.replace(rendered, destination)
    print(f"READY {tier.code} yuan: {metadata}")


def print_plan(tiers: tuple[ListingTier, ...], force: bool) -> None:
    for tier in tiers:
        destination = OUTPUT_DIR / tier.filename
        action = (
            "replace"
            if destination.exists() and force
            else "skip"
            if destination.exists()
            else "create"
        )
        visibility = "public" if tier.public else "test"
        print(
            f"{action.upper():7} {tier.code:>3} yuan  {visibility:6}  "
            f"base={tier.base_points:<5} bonus={tier.bonus_points:<4} total={tier.total_points:<5}  "
            f"{destination.relative_to(ROOT)}"
        )


def main() -> int:
    args = parse_args()
    tiers = selected_tiers(args.only, args.include_test)

    if args.show_prompts:
        for tier in tiers:
            print(f"=== {tier.code} yuan / {tier.total_points} points ===")
            print(build_prompt(tier))
            print()

    if args.dry_run:
        print_plan(tiers, args.force)
        return 0

    font_path = resolve_font(args.font)
    print(f"FONT {font_path}")
    client = create_client(args.base_url)
    for tier in tiers:
        generate_one(client, tier, args.model, font_path, args.force)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:  # noqa: BLE001 - Keep API diagnostics concise and avoid printing secrets.
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
