import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  isPublicEfficiencyDataFallback,
  readEfficiencyDataSource,
} from './efficiency-data-source.mjs'
import { validateEfficiencySkillReferences } from './validate-efficiency-skill-refs.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(root, 'server/handlers/efficiency-data.json')
const skillSourcePath = resolve(root, 'tools/prts_logistics_skills.json')
const targetPath = resolve(root, 'server/handlers/.generated/data.ts')
const buildMetaPath = resolve(root, 'src/lib/.generated/build-meta.ts')
const packagePath = resolve(root, 'package.json')
const LINE_ENDING = '\n'

const source = await readEfficiencyDataSource(sourcePath)
const data = JSON.parse(source.replace(/^\uFEFF/, ''))
const skillData = JSON.parse((await readFile(skillSourcePath, 'utf8')).replace(/^\uFEFF/, ''))
if (!isPublicEfficiencyDataFallback(source)) validateEfficiencySkillReferences(skillData, data)
const packageJson = JSON.parse(await readFile(packagePath, 'utf8'))
const sourceHash = createHash('sha256').update(source).digest('hex')
const baseVersion = String(packageJson.version || '0.0.0')
const refreshMetadata = shouldRefreshMetadata()
const existingFrontendVersion = await readExistingBuildMetaField('frontend_version')
const existingBackendVersion = await readExistingBuildMetaField('backend_version')
const existingDataVersion = await readExistingBuildMetaField('data_version')
const existingGeneratedAt = await readExistingBuildMetaField('generated_at')
const existingSourceSummary = await readExistingBuildMetaField('source_summary')
const existingGitSha = await readExistingBuildMetaField('git_sha')
const existingBuildContext = await readExistingBuildMetaField('build_context')
const defaultBuildVersion = normalizeBaseVersion(baseVersion)
const gitSha = resolveGitSha(existingGitSha, refreshMetadata)
const buildNumber = refreshMetadata ? resolveBuildNumber() : null
const generatedBuildVersion = resolveGeneratedBuildVersion(baseVersion, buildNumber)
const dataVersion = process.env.DATA_VERSION || resolveGeneratedDataVersion(
  sourceHash,
  refreshMetadata ? buildNumber : null,
  refreshMetadata ? gitSha : null,
)
const sourceSummary = buildSourceSummary(data, sourceHash)
const canReuseGeneratedAt = !refreshMetadata && existingDataVersion === dataVersion && existingSourceSummary === sourceSummary
const generatedAt = process.env.GENERATED_AT ||
  (canReuseGeneratedAt ? existingGeneratedAt : null) ||
  new Date().toISOString()
const appBuildMeta = {
  frontend_version: process.env.FRONTEND_VERSION || process.env.APP_VERSION || generatedBuildVersion || existingFrontendVersion || defaultBuildVersion,
  backend_version: process.env.BACKEND_VERSION || process.env.APP_VERSION || generatedBuildVersion || existingBackendVersion || defaultBuildVersion,
  data_version: dataVersion,
  generated_at: generatedAt,
  source_summary: sourceSummary,
  git_sha: gitSha,
  build_context: (refreshMetadata ? process.env.BUILD_CONTEXT : null) ||
    (refreshMetadata && buildNumber ? process.env.GITHUB_EVENT_NAME || process.env.CONTEXT : existingBuildContext) ||
    (process.env.CI ? 'ci' : 'local'),
}
const dataMetadata = {
  data_version: appBuildMeta.data_version,
  generated_at: appBuildMeta.generated_at,
  source_summary: appBuildMeta.source_summary,
}
const output = [
  '// Auto-generated from efficiency-data.json',
  '// Do not edit this file directly. Update efficiency-data.json and run npm run generate:data.',
  `export const EFFICIENCY_DATA_METADATA = ${JSON.stringify(dataMetadata)} as const;`,
  `export const EFFICIENCY_DATA: Record<string, unknown> = ${JSON.stringify(data)};`,
  '',
].join(LINE_ENDING)

await writeFileIfChanged(targetPath, output)

const buildMetaOutput = [
  '// Auto-generated by scripts/generate-data.mjs',
  '// Do not edit this file directly.',
  `export const APP_BUILD_META = ${JSON.stringify(appBuildMeta, null, 2).replace(/\n/g, LINE_ENDING)} as const;`,
  '',
  'export type AppBuildMeta = typeof APP_BUILD_META;',
  '',
].join(LINE_ENDING)

await writeFileIfChanged(buildMetaPath, buildMetaOutput)

function shouldRefreshMetadata() {
  return process.argv.includes('--refresh-metadata') ||
    ['1', 'true', 'yes'].includes(String(process.env.REFRESH_BUILD_METADATA || '').toLowerCase())
}

function normalizeBaseVersion(baseVersion) {
  const match = baseVersion.match(/^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/)
  if (!match) return baseVersion

  const [, major, minor, patch] = match
  return `${major}.${minor}.${patch}`
}

function resolveGeneratedBuildVersion(baseVersion, buildNumber) {
  if (!buildNumber) return null
  const match = baseVersion.match(/^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/)
  if (!match) return `${baseVersion}.${buildNumber}`

  const [, major, minor] = match
  return `${major}.${minor}.${buildNumber}`
}

function resolveGeneratedDataVersion(hash, buildNumber, gitSha) {
  const shortSha = gitSha ? gitSha.slice(0, 7) : null
  if (buildNumber && shortSha) return `data.${buildNumber}.${shortSha}`
  if (buildNumber) return `data.${buildNumber}`
  return `data.${hash.slice(0, 12)}`
}

function resolveBuildNumber() {
  for (const key of ['VERSION_PATCH', 'BUILD_NUMBER']) {
    const value = readPositiveIntegerEnv(key)
    if (value) return value
  }
  return readGitCommitCount()
}

function readPositiveIntegerEnv(key) {
  const rawValue = process.env[key]
  if (!rawValue) return null
  const value = rawValue.trim()
  if (!/^\d+$/.test(value)) return null
  return String(Number(value))
}

function resolveGitSha(existingGitSha, refreshMetadata) {
  for (const key of ['VERSION_SOURCE_SHA', 'GIT_SHA', 'COMMIT_REF']) {
    const sha = normalizeGitSha(process.env[key])
    if (sha) return sha
  }
  if (refreshMetadata && process.env.CI) return normalizeGitSha(existingGitSha)
  return readGitSha() || normalizeGitSha(existingGitSha)
}

function normalizeGitSha(value) {
  if (!value) return null
  const sha = value.trim()
  return /^[0-9a-f]{7,40}$/i.test(sha) ? sha : null
}

function readGitSha() {
  const result = spawnSync('git', ['rev-parse', 'HEAD'], {
    cwd: root,
    encoding: 'utf8',
  })
  if (result.status !== 0) return null
  return result.stdout.trim() || null
}

function readGitCommitCount() {
  const result = spawnSync('git', ['rev-list', '--count', 'HEAD'], {
    cwd: root,
    encoding: 'utf8',
  })
  if (result.status !== 0) return null
  const value = result.stdout.trim()
  return /^\d+$/.test(value) ? String(Number(value)) : null
}

async function writeFileIfChanged(filePath, content) {
  try {
    if (await readFile(filePath, 'utf8') === content) return
  } catch {
    // First generation should write the generated file.
  }

  await mkdir(dirname(filePath), { recursive: true })
  const temporaryPath = `${filePath}.tmp-${process.pid}`
  try {
    await writeFile(temporaryPath, content, 'utf8')
    await rename(temporaryPath, filePath)
  } finally {
    await rm(temporaryPath, { force: true })
  }
}

async function readExistingBuildMetaField(fieldName) {
  try {
    const content = await readFile(buildMetaPath, 'utf8')
    return readJsonStringField(content, fieldName)
  } catch {
    return null
  }
}

function readJsonStringField(content, fieldName) {
  const fieldPattern = new RegExp(`"${escapeRegExp(fieldName)}"\\s*:\\s*("(?:\\\\.|[^"\\\\])*")`)
  const match = content.match(fieldPattern)
  if (!match) return null
  return JSON.parse(match[1])
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function buildSourceSummary(rawData, hash) {
  const workplaces = rawData.workplaces ?? {}
  const tradingRules = rawData.combination_rules?.trading_station ?? {}
  const manufacturingRules = rawData.combination_rules?.manufacturing_station ?? {}
  const controlRules = rawData.control_center_rules ?? []
  const workplaceCount = Object.values(workplaces).reduce((count, value) => {
    if (Array.isArray(value)) return count + value.length
    return count + (value ? 1 : 0)
  }, 0)

  return [
    'source=server/handlers/efficiency-data.json',
    `sha256=${hash.slice(0, 12)}`,
    `workplaces=${workplaceCount}`,
    `trading_rule_groups=${Object.keys(tradingRules).length}`,
    `manufacturing_rule_groups=${Object.keys(manufacturingRules).length}`,
    `control_center_rules=${Array.isArray(controlRules) ? controlRules.length : 0}`,
  ].join('; ')
}
