import { copy } from '../../../copy'
import { useBalance, formatPoints } from '../../tool/dashboard/BalanceSection'
import { useCommercialProfiles } from '../../tool/dashboard/CommercialProfilesSection'
import { getMeteredBillingPolicy } from '../../../lib/metered-billing'
import { useInternalHref } from '../../../components/InternalLink'
import type { V2Session } from '../OptionsDrawer'
import { EmptyState, Facts, Field, Loading, Notice, SectionTitle } from '../components/WorkspaceUI'

export function Balance({ redemptionEnabled }: { redemptionEnabled: boolean }) {
  const m = useBalance()
  const resolve = useInternalHref()
  const policy = getMeteredBillingPolicy()
  const text = copy.balance
  if (!m.page) return m.loading ? <Loading label={text.loading} /> : <Notice error>{m.error ?? text.load_failed}<button className="v2-text-button" onClick={() => void m.load()}>{text.retry}</button></Notice>
  const debt = m.page.balance.debt ?? '0.00'
  const commercial = m.page.balance.commercial
  return <div className="v2-balance-workspace"><section className="v2-balance-summary"><div><span className="v2-label">{text.available}</span><strong>{formatPoints(m.page.balance.available ?? '0.00')}</strong><small>{text.unit}</small></div><Facts items={[[text.reserved, formatPoints(m.page.balance.reserved ?? '0.00')], [text.lifetime_credited, formatPoints(m.page.balance.lifetime_credited ?? '0.00')], ...(debt !== '0.00' ? [[text.debt, formatPoints(debt)] as [string, string]] : [])]} /></section><p className="v2-lead">{text.description}</p><Notice error>{m.error}{m.errorTarget && <a href={resolve(m.errorTarget)}>{text.go_to_redeem}</a>}</Notice><Notice>{m.notice}</Notice>
    <div className="v2-balance-controls"><section><SectionTitle title={copy.metered.balance.personal_price_label} /><p>{copy.metered.balance.personal_price_value(formatPoints(policy.personal.main_schedule_points))}</p>{commercial && <p>{debt !== '0.00' ? copy.metered.balance.commercial_debt(commercial.level, formatPoints(debt)) : commercial.eligible ? copy.metered.balance.commercial_eligible(commercial.level, formatPoints(commercial.charge_points)) : copy.metered.balance.commercial_locked(formatPoints(commercial.points_to_next_level ?? commercial.threshold_points ?? '10000.00'))}</p>}{commercial?.eligible && commercial.next_threshold_points && <p>{copy.metered.balance.next_level(formatPoints(commercial.points_to_next_level ?? '0.00'), formatPoints(commercial.next_threshold_points))}</p>}</section>
    {redemptionEnabled && <form onSubmit={m.redeem}><SectionTitle title={text.redeem_title} description={text.redeem_description} /><Field label={text.redeem_placeholder} value={m.cdk} required onChange={(event) => { m.setCdk(event.target.value); m.setPending(null) }} /><button type="submit" className="v2-button v2-button-primary" disabled={m.redeeming}>{m.redeeming ? text.redeeming : text.redeem}</button></form>}</div>
    <section><SectionTitle title={text.history} />{!m.page.transactions.length ? <EmptyState title={text.empty} /> : <ol className="v2-balance-ledger">{m.page.transactions.map((transaction) => <li key={transaction.id}><time>{new Date(transaction.created_at).toLocaleString('zh-CN')}</time><strong>{text[transaction.kind]}</strong><b data-debit={transaction.amount.startsWith('-')}>{transaction.amount.startsWith('-') ? formatPoints(transaction.amount) : `+${formatPoints(transaction.amount)}`}</b><small>{copy.metered.balance.transaction_balance(formatPoints(transaction.balance_after))}</small></li>)}</ol>}{m.page.next_cursor && <button className="v2-button v2-button-secondary" disabled={m.loadingMore} onClick={() => void m.load(m.page!.next_cursor)}>{m.loadingMore ? text.loading : text.load_more}</button>}</section>
  </div>
}

export function Commercial({ onOpen }: { onOpen: (profile: V2Session['profiles'][number]) => Promise<void> }) {
  const m = useCommercialProfiles()
  const text = copy.metered.commercial_profiles
  return <div className="v2-commercial-workspace"><SectionTitle title={text.title} description={text.description} action={<button className="v2-button v2-button-primary" disabled={!m.page || m.busy === 'create' || m.page.limits.suspended} onClick={() => void m.create()}>{m.busy === 'create' ? text.creating : text.create}</button>} />{m.page && <Facts items={[[copy.v2.activeProfiles, `${m.page.limits.active}/${m.page.limits.active_limit}`], [copy.v2.totalProfiles, `${m.page.limits.total}/${m.page.limits.total_limit}`]]} />}{m.page?.limits.suspended && <Notice>{text.suspended(m.page.limits.suspension_reason ?? text.default_suspension_reason)}</Notice>}<Notice error>{m.error}{m.error && !m.page && <button className="v2-text-button" onClick={() => void m.load()}>{text.retry}</button>}</Notice><Notice>{m.notice}</Notice>
    <form onSubmit={m.search} className="v2-commercial-filter"><label className="v2-field"><span>{copy.v2.profiles}</span><select className="v2-input" value={m.state} onChange={(event) => { m.setPage(null); m.setState(event.target.value as 'active' | 'archived') }}><option value="active">{text.active_filter}</option><option value="archived">{text.archived_filter}</option></select></label><Field label={text.search_placeholder} value={m.draftQuery} onChange={(event) => m.setDraftQuery(event.target.value)} /><button className="v2-button v2-button-secondary" type="submit">{text.search}</button></form>
    {m.state === 'active' && m.activeProfiles.length > 0 && <div className="v2-actions"><label className="v2-check"><input type="checkbox" checked={m.allVisibleSelected} onChange={(event) => m.setSelectedIds(event.target.checked ? new Set(m.activeProfiles.map((profile) => profile.id)) : new Set())} />{text.select_all_loaded}</label><button className="v2-text-button" disabled={m.selectedIds.size === 0 || m.busy !== null} onClick={() => void m.batchArchive()}>{m.busy === 'batch' ? text.archiving : text.batch_archive(m.selectedIds.size)}</button></div>}
    {m.loading && !m.page ? <Loading label={text.loading} /> : !m.page?.profiles.length ? <EmptyState title={text.empty} /> : <div className="v2-commercial-list">{m.page.profiles.map((profile) => <article key={profile.id}>{m.editDraft?.profileId === profile.id ? <form className="v2-inline-editor" onSubmit={(event) => { event.preventDefault(); void m.saveEdit() }}><Field label={text.name_label} maxLength={40} value={m.editDraft.displayName} onChange={(event) => m.setEditDraft({ ...m.editDraft!, displayName: event.target.value })} /><label className="v2-field"><span>{text.note_label}</span><textarea className="v2-input" rows={3} maxLength={500} value={m.editDraft.note} onChange={(event) => m.setEditDraft({ ...m.editDraft!, note: event.target.value })} /></label><div className="v2-actions"><button className="v2-button v2-button-primary" disabled={m.busy === profile.id}>{text.save}</button><button type="button" className="v2-text-button" disabled={m.busy === profile.id} onClick={() => m.setEditDraft(null)}>{text.cancel}</button></div></form> : <><div className="v2-commercial-name">{m.state === 'active' && <input type="checkbox" aria-label={text.select_profile(profile.display_name)} checked={m.selectedIds.has(profile.id)} onChange={(event) => { const checked = event.target.checked; m.setSelectedIds((current) => { const next = new Set(current); checked ? next.add(profile.id) : next.delete(profile.id); return next }) }} />}<div><h3>{profile.display_name}</h3><p>{profile.note || text.no_note}</p></div></div><div className="v2-actions">{!profile.archived_at && <button className="v2-button v2-button-secondary" onClick={() => void onOpen(profile)}>{text.open_workspace}</button>}<button className="v2-text-button" disabled={m.busy === profile.id} onClick={() => m.setEditDraft({ profileId: profile.id, displayName: profile.display_name, note: profile.note ?? '' })}>{text.edit}</button><button className="v2-text-button" disabled={m.busy === profile.id} onClick={() => void m.mutate(profile, profile.archived_at ? 'restore' : 'archive')}>{profile.archived_at ? text.restore : text.archive}</button><button className="v2-text-button v2-danger" disabled={m.busy === profile.id} onClick={() => void m.mutate(profile, 'delete')}>{text.permanent_delete}</button></div></>}</article>)}</div>}{m.page?.next_cursor && <button className="v2-button v2-button-secondary" disabled={m.loading} onClick={() => void m.load(m.page!.next_cursor)}>{text.load_more}</button>}
  </div>
}
