import { useEffect, useMemo, useState } from 'react'
import { Plus, X } from 'lucide-react'
import { copy, CURRENT_LOCALE } from '../../../copy'
import { expandScenarioComparison, SCENARIO_COMPARISON_MAX_ADDITIONAL_CONFIGS, type ScenarioComparisonFactors, type ScenarioComparisonPoint, type ScenarioLayout } from '../../../lib/scenario-comparison'
import { useScenarioComparison } from '../../tool/optimize/scenario-lab/useScenarioComparison'
import { LAYOUTS, SCHEDULES, DRONES, buildPlan, planLabel, planKey } from '../../tool/optimize/scenario-lab/ScenarioFactors'
import ScenarioParetoChart from '../../tool/optimize/scenario-lab/ScenarioParetoChart'
import ScheduleProgress from '../../../components/ScheduleProgress'
import type { V2Workflow } from '../WorkspaceSections'
import { EmptyState, Facts, Notice, SectionTitle } from '../components/WorkspaceUI'
import Link from '../../../components/InternalLink'
import { useSiteFeatures } from '../../../lib/site-feature-context'
import { productPolicies } from '../../../lib/product-catalog'

const text = copy.optimize

export default function Comparison({ workflow: w, onConfig }: { workflow: V2Workflow; onConfig: () => void }) {
  return w.userCanUseScenarioLab ? <ComparisonWorkspace workflow={w} onConfig={onConfig} /> : <ComparisonPreview />
}

function ComparisonWorkspace({ workflow: w, onConfig }: { workflow: V2Workflow; onConfig: () => void }) {
  const model = useScenarioComparison({ profileId: w.profile.id, operators: w.mergedOperators, config: w.activeConfig, onSettled: w.refreshInventory })
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const expansion = useMemo(() => { try { return { value: expandScenarioComparison(w.activeConfig, model.factors), error: null } } catch (caught) { return { value: null, error: caught instanceof Error ? caught.message : String(caught) } } }, [w.activeConfig, model.factors])
  useEffect(() => { if (model.result) setSelectedId((current) => model.result!.points.some((point) => point.id === current) ? current : model.result!.frontierScenarioIds[0] ?? model.result!.points.find((point) => point.status === 'succeeded')?.id ?? null) }, [model.result])
  const selected = model.result?.points.find((point) => point.id === selectedId)
  const quoteUnavailable = w.scenarioQuoteRequired && (!w.scenarioBillingQuote || w.scenarioBillingQuoteLoading || !w.scenarioBillingQuote.sufficient)
  return <div className="v2-comparison-workspace"><section className="v2-experiment-builder"><SectionTitle title={text.pages_tool_optimize_ScenarioLabSection_002} description={text.pages_tool_optimize_ScenarioLabSection_003} /><Factors factors={model.factors} disabled={model.loading} onChange={model.setFactors} />
    <div className="v2-experiment-run"><div>{expansion.value ? <><strong>{text.pages_tool_optimize_ScenarioLabSection_007}{expansion.value.scenarios.length}{text.pages_tool_optimize_ScenarioLabSection_008}</strong><small>{text.pages_tool_optimize_ScenarioLabSection_004}{expansion.value.rawCombinationCount} {text.pages_tool_optimize_ScenarioLabSection_005}{expansion.value.skipped.reduce((sum, item) => sum + item.count, 0)} {text.pages_tool_optimize_ScenarioLabSection_006}</small></> : <Notice error>{expansion.error}</Notice>}</div><button className="v2-button v2-button-primary" disabled={model.loading || !expansion.value || quoteUnavailable} onClick={() => void model.run(false, w.scenarioBillingQuote)}>{model.loading ? text.pages_tool_optimize_ScenarioLabSection_010 : `${text.pages_tool_optimize_ScenarioLabSection_011}${expansion.value?.scenarios.length ?? 0}${text.pages_tool_optimize_ScenarioLabSection_012}`}</button></div>
    {expansion.value?.skipped.map((item) => <p className="v2-muted" key={`${item.code}:${item.droneStrategy}`}>{item.message}（{item.count} {text.pages_tool_optimize_ScenarioLabSection_009}</p>)}
    {w.scenarioQuoteRequired && <Notice>{w.scenarioBillingQuoteLoading ? text.pages_tool_optimize_ScenarioLabSection_055 : w.scenarioBillingQuoteError ?? (w.scenarioBillingQuote?.sufficient === false ? text.pages_tool_optimize_ScenarioLabSection_056 : text.pages_tool_optimize_ScenarioLabSection_057)}{w.scenarioBillingQuoteError && <button className="v2-text-button" onClick={() => void w.refreshScenarioBillingQuote()}>{text.pages_tool_optimize_ScenarioLabSection_058}</button>}</Notice>}
    <Notice error>{model.error}</Notice>
  </section>
  {model.progress && <div className="v2-experiment-progress"><ScheduleProgress progress={model.progress} variant="focus" />{model.canCancel && <button className="v2-button v2-button-secondary" disabled={model.cancelling} onClick={() => { if (window.confirm(text.pages_tool_optimize_ScenarioLabSection_052)) void model.cancel() }}>{model.cancelling ? text.pages_tool_optimize_ScenarioLabSection_053 : text.pages_tool_optimize_ScenarioLabSection_051}</button>}</div>}
  {!model.result && !model.progress && <EmptyState title={text.pages_tool_optimize_ScenarioLabSection_013}>{text.pages_tool_optimize_ScenarioLabSection_014}</EmptyState>}
  {model.result && <><Facts items={[[text.pages_tool_optimize_ScenarioLabSection_015, model.result.scenarioCount], [text.pages_tool_optimize_ScenarioLabSection_017, model.result.verifiedCount], [text.pages_tool_optimize_ScenarioLabSection_019, model.result.frontierScenarioIds.length]]} /><div className="v2-comparison-results"><section><SectionTitle title={text.pages_tool_optimize_ScenarioLabSection_023} description={text.pages_tool_optimize_ScenarioLabSection_024} /><ScenarioParetoChart points={model.result.points} selectedId={selectedId} onSelect={setSelectedId} /></section>{selected && <Selected point={selected} disabled={w.loading} onApply={() => { w.handleApplyScenarioConfig(selected.config); onConfig() }} />}</div>{model.result.warnings.map((warning) => <Notice key={warning}>{warning}</Notice>)}<SectionTitle title={text.pages_tool_optimize_ScenarioLabSection_025} description={text.pages_tool_optimize_ScenarioLabSection_026} /><div className="v2-comparison-list">{model.result.points.map((point) => <button key={point.id} aria-pressed={selectedId === point.id} onClick={() => setSelectedId(point.id)}><strong>{point.label}</strong><span>{(point.verified ?? point.screening)?.productionSanityPerDay.toLocaleString(CURRENT_LOCALE, { maximumFractionDigits: 1 }) ?? point.error ?? '—'}</span><small>{point.shiftHours.join(' / ')}h · {point.operationsPerDay}{text.pages_tool_optimize_ScenarioLabSection_030}{point.verified ? text.pages_tool_optimize_ScenarioLabSection_031 : text.pages_tool_optimize_ScenarioLabSection_032}</small></button>)}</div></>}
  </div>
}

function Factors({ factors, disabled, onChange }: { factors: ScenarioComparisonFactors; disabled: boolean; onChange: (next: ScenarioComparisonFactors) => void }) {
  const [layoutId, setLayoutId] = useState<ScenarioLayout>('243')
  const [orundum, setOrundum] = useState(0)
  const [shard, setShard] = useState(0)
  const [gold, setGold] = useState(2)
  const layout = LAYOUTS.find((item) => item.id === layoutId)!
  const draft = buildPlan(layout, Math.min(orundum, layout.trading), Math.min(shard, layout.manufacturing), Math.min(gold, layout.manufacturing - Math.min(shard, layout.manufacturing)))
  const count = factors.layouts.reduce((sum, entry) => sum + entry.plans.length, 0)
  const duplicate = factors.layouts.find((entry) => entry.layout === layoutId)?.plans.some((plan) => planKey(plan) === planKey(draft))
  return <fieldset className="v2-experiment-factors" disabled={disabled}><legend className="sr-only">{text.pages_tool_optimize_scenario_lab_ScenarioFactors_011}</legend>
    <div className="v2-production-builder"><div className="v2-production-inputs"><label className="v2-field"><span>{text.pages_tool_optimize_scenario_lab_ScenarioFactors_012}</span><select className="v2-input" value={layoutId} onChange={(event) => setLayoutId(event.target.value as ScenarioLayout)}>{LAYOUTS.map((item) => <option key={item.id}>{item.id}</option>)}</select></label>{[
      [text.pages_tool_optimize_scenario_lab_ScenarioFactors_020, Math.min(orundum, layout.trading), layout.trading, setOrundum],
      [text.pages_tool_optimize_scenario_lab_ScenarioFactors_021, Math.min(shard, layout.manufacturing), layout.manufacturing, setShard],
      [text.pages_tool_optimize_scenario_lab_ScenarioFactors_022, Math.min(gold, layout.manufacturing - Math.min(shard, layout.manufacturing)), layout.manufacturing - Math.min(shard, layout.manufacturing), setGold],
    ].map(([label, value, max, update]) => <label key={String(label)} className="v2-field"><span>{String(label)}</span><select className="v2-input" value={value as number} onChange={(event) => (update as (value: number) => void)(Number(event.target.value))}>{Array.from({ length: Number(max) + 1 }, (_, i) => <option key={i}>{i}</option>)}</select></label>)}</div><p>{planLabel(draft)}</p><button className="v2-button v2-button-secondary" disabled={duplicate || count >= SCENARIO_COMPARISON_MAX_ADDITIONAL_CONFIGS} onClick={() => {
      const layouts = factors.layouts.filter((item) => item.layout !== layoutId)
      layouts.push({ layout: layoutId, plans: [...(factors.layouts.find((item) => item.layout === layoutId)?.plans ?? []), draft].sort((a, b) => planKey(a).localeCompare(planKey(b))) })
      onChange({ ...factors, layouts: layouts.sort((a, b) => a.layout.localeCompare(b.layout)) })
    }}><Plus size={16} />{duplicate ? text.pages_tool_optimize_scenario_lab_ScenarioFactors_023 : count >= SCENARIO_COMPARISON_MAX_ADDITIONAL_CONFIGS ? text.pages_tool_optimize_scenario_lab_ScenarioFactors_034(SCENARIO_COMPARISON_MAX_ADDITIONAL_CONFIGS) : text.pages_tool_optimize_scenario_lab_ScenarioFactors_024}</button><small>{text.pages_tool_optimize_scenario_lab_ScenarioFactors_033(count, SCENARIO_COMPARISON_MAX_ADDITIONAL_CONFIGS)}</small><ul className="v2-production-plans">{factors.layouts.flatMap((entry) => entry.plans.map((plan) => <li key={`${entry.layout}:${planKey(plan)}`}><b>{entry.layout}</b><span>{planLabel(plan)}</span><button className="v2-icon-button" aria-label={`${text.pages_tool_optimize_scenario_lab_ScenarioFactors_026}${entry.layout} ${planLabel(plan)}`} onClick={() => onChange({ ...factors, layouts: factors.layouts.map((row) => row.layout === entry.layout ? { ...row, plans: row.plans.filter((item) => planKey(item) !== planKey(plan)) } : row).filter((row) => row.plans.length > 0) })}><X size={16} /></button></li>))}</ul></div>
    <div className="v2-experiment-options"><fieldset><legend>{text.pages_tool_optimize_scenario_lab_ScenarioFactors_014}</legend>{SCHEDULES.map((item) => <label className="v2-check" key={item.id}><input type="checkbox" checked={factors.maaSchedules.includes(item.id)} onChange={() => onChange({ ...factors, maaSchedules: factors.maaSchedules.includes(item.id) ? factors.maaSchedules.filter((id) => id !== item.id) : [...factors.maaSchedules, item.id].sort((a, b) => ['variable', '8x3'].indexOf(a) - ['variable', '8x3'].indexOf(b)) })} />{item.label}</label>)}<label className="v2-check"><input type="checkbox" checked={factors.includeRotation} onChange={() => onChange({ ...factors, includeRotation: !factors.includeRotation })} />{text.pages_tool_optimize_scenario_lab_ScenarioFactors_015}</label><small>{text.pages_tool_optimize_scenario_lab_ScenarioFactors_016}</small></fieldset><fieldset><legend>{text.pages_tool_optimize_scenario_lab_ScenarioFactors_017}</legend>{DRONES.map((item) => <label className="v2-check" key={item.id}><input type="checkbox" checked={factors.droneStrategies.includes(item.id)} onChange={() => onChange({ ...factors, droneStrategies: factors.droneStrategies.includes(item.id) ? factors.droneStrategies.filter((id) => id !== item.id) : [...factors.droneStrategies, item.id] })} />{item.label}</label>)}<small>{text.pages_tool_optimize_scenario_lab_ScenarioFactors_018}</small></fieldset></div>
  </fieldset>
}

function Selected({ point, disabled, onApply }: { point: ScenarioComparisonPoint; disabled: boolean; onApply: () => void }) {
  const value = point.verified ?? point.screening
  const economy = value?.orundumEconomy
  const format = (n: number) => n.toLocaleString(CURRENT_LOCALE, { maximumFractionDigits: 1 })
  return <aside className="v2-comparison-selected"><span className="v2-label">{text.pages_tool_optimize_ScenarioLabSection_027}</span><h3>{point.label}</h3><Facts items={[[text.pages_tool_optimize_ScenarioLabSection_028, value ? format(value.productionSanityPerDay) : '—'], [text.pages_tool_optimize_ScenarioLabSection_029, point.shiftHours.join(' / ')], [text.pages_tool_optimize_ScenarioLabSection_030, point.operationsPerDay]]} />{!value && <Notice error>{point.error}</Notice>}{value && point.scheduleStrategy === 'variable' && <p className="v2-muted">{point.variableShiftFallback ? text.pages_tool_optimize_ScenarioLabSection_033 : text.pages_tool_optimize_ScenarioLabSection_034}</p>}{economy && <Facts items={[[text.pages_tool_optimize_ScenarioLabSection_035, `${format(economy.sustainablePerDay)} / ${format(economy.shortTermPerDay)}`], [text.pages_tool_optimize_ScenarioLabSection_036, `${format(economy.opportunityCostSanityPerDay)}${text.pages_tool_optimize_ScenarioLabSection_037}`], [text.pages_tool_optimize_ScenarioLabSection_038, economy.inventoryDepletionDays == null ? '—' : `${format(economy.inventoryDepletionDays)}${text.pages_tool_optimize_ScenarioLabSection_039}`], [text.pages_tool_optimize_ScenarioLabSection_040, `${({ capacity_limited: text.pages_tool_optimize_ScenarioLabSection_044, budget_limited: text.pages_tool_optimize_ScenarioLabSection_045, inventory_burst: text.pages_tool_optimize_ScenarioLabSection_046 })[economy.case]} · ${({ orirock_budget: text.pages_tool_optimize_ScenarioLabSection_047, manufacture: text.pages_tool_optimize_ScenarioLabSection_048, trading: text.pages_tool_optimize_ScenarioLabSection_049, inventory: text.pages_tool_optimize_ScenarioLabSection_050 })[economy.bottleneck]}${text.pages_tool_optimize_ScenarioLabSection_041}${format(economy.dailySanityBudget)}${economy.monthlyCard ? text.pages_tool_optimize_ScenarioLabSection_042 : ''}`]]} />}<button className="v2-button v2-button-primary" disabled={disabled || !value} onClick={onApply}>{text.pages_tool_optimize_ScenarioLabSection_043}</button></aside>
}

function ComparisonPreview() {
  const { features } = useSiteFeatures()
  return <div className="v2-comparison-preview"><SectionTitle title={text.paid_preview.lab_title} description={text.paid_preview.lab_description} /><fieldset disabled className="v2-preview-fields"><legend>{text.paid_preview.readonly}</legend><label className="v2-field"><span>{text.paid_preview.baseline}</span><input className="v2-input" value={text.paid_preview.baseline} readOnly /></label><label className="v2-field"><span>{text.paid_preview.alternative}</span><select className="v2-input"><option>{text.paid_preview.add}</option></select></label><button className="v2-button v2-button-secondary">{text.paid_preview.run}</button></fieldset><Notice>{text.paid_preview.pending}</Notice><p>{text.paid_preview.lab_detail}</p><p>{text.paid_preview.quotas(productPolicies.metered_billing.scenario_quotas.month, productPolicies.metered_billing.scenario_quotas.half_year, productPolicies.metered_billing.scenario_quotas.year)}</p>{features.pricing && <Link className="v2-text-button" to="/pricing">{text.paid_preview.compare}</Link>}</div>
}
