import { useMemo, useState } from 'react'
import { ArrowRight, RotateCcw, X } from 'lucide-react'
import { copy } from '../../../copy'
import type { CultivationCandidate, CultivationData, CultivationOptions } from '../../../lib/cultivation-contract'
import { useCultivation } from '../../CultivationPlanPage'
import { number, progress } from '../../cultivation/CultivationResults'
import { useSpecialItems } from '../../cultivation/CultivationSpecialItems'
import type { V2Session } from '../OptionsDrawer'
import { v2Path } from '../navigation'
import Link from '../../../components/InternalLink'
import { EmptyState, Facts, Field, Notice, SectionTitle } from '../components/WorkspaceUI'

type Model = ReturnType<typeof useCultivation>
const text = copy.tools.cultivation

export default function Cultivation({ session }: { session: V2Session }) {
  const m = useCultivation(session)
  const [view, setView] = useState('priorities')
  return <div className="v2-cultivation-workspace"><div className="v2-tool-source"><div><span className="v2-label">{copy.v2.toolSource}</span><p>{text.description}</p></div>{session.authStatus === 'authenticated' && m.profiles.length ? <><label className="v2-field"><span>{text.profile}</span><select className="v2-input" value={m.profileId} onChange={(event) => m.setChosenProfile(event.target.value)}>{m.profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name}</option>)}</select></label><button className="v2-button v2-button-primary" disabled={m.busy} onClick={() => void m.load()}>{m.busy ? text.loadingData : text.load}<ArrowRight size={16} /></button></> : <div><p>{session.authStatus === 'authenticated' ? text.noProfile : text.login}</p><Link className="v2-button v2-button-secondary" to={v2Path('profiles', session.activeProfile?.id)}>{text.loginAction}</Link></div>}</div>
    <Notice error>{m.error}</Notice>
    {m.data && m.plan ? <><Facts items={[[text.stats.homeworks, number(m.data.stats.homeworks)], [text.stats.owned, number(m.data.stats.owned)], [text.stats.satisfied, number(m.data.candidates.filter((row) => row.satisfied).length)], [text.stats.incomplete, number(m.data.stats.incomplete)]]} />{m.data.warnings.map((warning) => <Notice key={warning}>{warning}</Notice>)}<div className="v2-planning-workspace">
      <aside className="v2-planning-conditions"><SectionTitle title={copy.v2.toolParameters} />
        <fieldset className="v2-choice-list"><legend>{text.preference}</legend>{Object.entries(text.preferences).map(([key, title]) => <label key={key}><input type="radio" name="v2-cultivation-preference" checked={m.options.preference === key} onChange={() => m.setOptions((options) => ({ ...options, preference: key as CultivationOptions['preference'] }))} /><span><strong>{title}</strong><small>{text.preferenceHints[key as CultivationOptions['preference']]}</small></span></label>)}</fieldset>
        {m.options.preference === 'community' && m.data.community?.status !== 'fresh' && <Notice>{m.data.community?.status === 'stale' ? text.communityStale : text.communityUnavailable}</Notice>}
        {([['dailySanity', text.daily, 0, 2000], ['days', text.days, 1, 180], ['limit', text.limit, 1, 30]] as const).map(([key, title, min, max]) => <Field key={key} label={title} type="number" min={min} max={max} value={m.numbers[key]} onChange={(event) => m.setNumbers((prior) => ({ ...prior, [key]: event.target.value }))} />)}
        <Field label={text.start} type="date" value={m.options.startDate} onChange={(event) => m.setOptions((options) => ({ ...options, startDate: event.target.value }))} />
        <p className="v2-muted">{text.dailyHint}</p><label className="v2-check"><input type="checkbox" checked={m.options.allOpen} onChange={(event) => m.setOptions((options) => ({ ...options, allOpen: event.target.checked }))} />{text.allOpen}</label><small className="v2-muted">{text.allOpenHint}</small>
        <details className="v2-disclosure"><summary>{text.potions}</summary><p>{text.potionHint}</p>{!m.data.potions.length ? <p>{text.noPotions}</p> : m.data.potions.map((potion) => <Field key={potion.key} label={potion.name} help={`${text.potionAmount(potion.count, potion.sanity)} · ${potion.expiresAt ? new Date(potion.expiresAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : text.expiryUnknown}${potion.sanity === null ? ` · ${text.potionUnknown}` : ''}`} type="number" min={0} max={potion.count} disabled={potion.sanity === null || Boolean(potion.expiresAt && Date.parse(potion.expiresAt) <= Date.now())} value={m.potionNumbers[potion.key] ?? '0'} onChange={(event) => m.setPotionNumbers((prior) => ({ ...prior, [potion.key]: event.target.value }))} />)}</details>
        <button className="v2-button v2-button-primary" onClick={m.apply}>{text.apply}</button>{m.changed && <Notice>{text.settingsChanged}</Notice>}
      </aside>
      <div className="v2-planning-outcome"><nav className="v2-view-switch" aria-label={copy.v2.toolOutcome}>{[['priorities', text.suggestions], ['materials', text.summary], ['calendar', text.calendar], ['comparison', text.comparison], ['special', text.specialItems]].map(([id, title]) => <button key={id} aria-pressed={view === id} onClick={() => setView(id)}>{title}</button>)}</nav>
        <section hidden={view !== 'priorities'}><p className="v2-muted">{text.adviceHint}</p>{!m.plan.selected.length ? <EmptyState title={text.empty} /> : <ol className="v2-cultivation-priorities">{m.plan.selected.map(({ candidate: row, allocation, estimatedDate }, index) => <li key={row.key}><span className="v2-step-number">{index + 1}</span><div><Operator row={row} /><p>{text.current} · {progress(row)}</p><p>{row.source === 'community' ? text.communityTarget : text.target} · {progress(row, true)}</p>{row.moduleName && <p>{row.moduleName} · {text.moduleRank(row.target.moduleLevel)}</p>}<small>{row.source === 'community' ? text.communityRate(row.communityRate ?? null) : `${text.demand} ${number(row.frequency)} · ${text.stageCount} ${row.stageCount}`}</small><Community row={row} data={m.data!} /><Facts items={[[text.cost, allocation.sanity === null ? text.unpriced : number(allocation.sanity)], [text.materialDate, estimatedDate ?? text.pending]]} /><p>{Object.entries(allocation.missing).map(([id, count]) => `${m.data!.itemNames[id] ?? id} × ${number(count)}`).join(' · ') || text.ready}</p>{allocation.exchanges.map((exchange) => <p key={exchange.item}>{text.exchange} · {text.exchangeAmount(exchange.count, exchange.cost)}</p>)}<div className="v2-actions">{row.examples.map((id) => <a className="v2-text-button" key={id} href={`https://prts.plus/?op=${id}`} target="_blank" rel="noreferrer">{text.example} #{id}</a>)}</div></div><button className="v2-icon-button" aria-label={`${text.exclude} ${row.name}`} onClick={() => m.exclude(row.operatorId, true)}><X size={18} /></button></li>)}</ol>}</section>
        <section hidden={view !== 'materials'}><Facts items={[[text.totalTraining, m.plan.totalTrainingSanity === null ? text.unpriced : number(m.plan.totalTrainingSanity)], [text.total, m.plan.totalSanity === null ? text.unpriced : number(m.plan.totalSanity)]]} /><SectionTitle title={text.totalMaterials} /><Materials items={m.plan.totalMaterials} data={m.data} /><SectionTitle title={text.missingMaterials} /><Materials items={m.plan.missingMaterials} data={m.data} />{m.plan.blocked.length > 0 && <><Notice>{text.blocked} · {text.blockedHint}</Notice><Materials items={Object.fromEntries(m.plan.blocked.map((task) => [task.item, m.plan!.missingMaterials[task.item]]))} data={m.data} /></>}</section>
        <section hidden={view !== 'calendar'}><p className="v2-muted">{text.calendarHint}</p><div className="v2-cultivation-calendar">{m.plan.days.map((day) => <article key={day.date}><div><time>{day.date}</time><small>{text.budget(day.spent, day.budget)}</small></div><div>{!day.farms.length && <p>{text.noFarms}</p>}{day.farms.map((farm) => <p key={`${farm.item}:${farm.stage}`}><strong>{farm.stage}</strong> · {m.data!.itemNames[farm.item] ?? farm.item}<small>{text.runs(farm.runs, number(farm.expectedQuantity))}</small></p>)}{day.potions.map((potion) => <small key={potion.name}>{potion.name} × {potion.count}</small>)}</div></article>)}</div>{m.plan.remaining.length > 0 && <Notice>{text.remaining} · {m.plan.remaining.map((task) => `${m.data!.itemNames[task.item] ?? task.item} × ${number(task.remaining)}`).join(' · ')}</Notice>}</section>
        <section hidden={view !== 'comparison'}><CandidateComparison model={m} data={m.data} /></section>
        <section hidden={view !== 'special'}><SpecialItems key={m.profileId} data={m.data} plan={m.plan} preference={m.appliedOptions.preference} /></section>
      </div>
    </div><p className="v2-data-date">{text.dataDate} · {new Date(m.data.updatedAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}<br />{text.importDate} · {new Date(m.data.importedAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}</p></> : !m.busy && <EmptyState title={text.load}>{text.description}</EmptyState>}
  </div>
}

function Operator({ row }: { row: CultivationCandidate }) {
  return <div className="v2-cultivation-operator"><img src={`/webp96/${encodeURIComponent(row.operatorId)}.webp`} alt="" width={48} height={48} loading="lazy" /><div><h3>{row.name}</h3><span>{text.skillName(row.target.skill)}{row.target.skillLevel > 7 && ` · ${text.masteryName(row.target.skillLevel - 7)}`}</span></div></div>
}

function Materials({ items, data }: { items: Record<string, number>; data: CultivationData }) {
  return Object.keys(items).length ? <dl className="v2-material-list">{Object.entries(items).map(([id, count]) => <div key={id}><dt>{data.itemNames[id] ?? id}</dt><dd>{number(count)}</dd></div>)}</dl> : <p className="v2-muted">{text.ready}</p>
}

function Community({ row, data }: { row: CultivationCandidate; data: CultivationData }) {
  const stats = data.community?.operators[row.operatorId]
  if (!stats) return null
  const percent = (value: number) => `${(value * 100).toFixed(1)}%`
  return <details className="v2-disclosure"><summary>{text.communityTitle} · {text.eliteRate} {percent(stats.elite[2])}</summary><p>{text.communitySample(stats.owned)}</p><dl className="v2-material-list">{stats.skills.map((skill, index) => <div key={index}><dt>{text.skillName(index + 1)}</dt><dd>{[1, 2, 3].map((rank) => `${text.masteryName(rank)} ${percent(skill[rank] ?? 0)}`).join(' · ')}</dd></div>)}{Object.entries(stats.modules).filter(([, ranks]) => ranks.slice(1).some((value) => value > 0)).map(([type, ranks]) => <div key={type}><dt>{text.moduleType(type)}</dt><dd>{text.moduleRate} {percent(ranks.slice(1).reduce((sum, value) => sum + value, 0))}<br />{[1, 2, 3].map((rank) => `${text.moduleRank(rank)} ${percent(ranks[rank] ?? 0)}`).join(' · ')}</dd></div>)}</dl></details>
}

function CandidateComparison({ model: m, data }: { model: Model; data: CultivationData }) {
  const [search, setSearch] = useState('')
  const [visible, setVisible] = useState(50)
  const rows = useMemo(() => data.candidates.filter((row) => row.name.includes(search)).sort((a, b) => b.frequency - a.frequency), [data, search])
  return <><p className="v2-muted">{text.comparisonHint}</p><Field label={text.search} value={search} onChange={(event) => { setSearch(event.target.value); setVisible(50) }} /><div className="v2-candidate-list">{rows.slice(0, visible).map((row) => <article key={row.key}><Operator row={row} /><div><strong>{row.satisfied ? text.matched : row.warnings.length ? text.check : text.needsTraining}</strong><p>{text.current} · {progress(row)}<br />{row.source === 'community' ? text.communityTarget : text.target} · {progress(row, true)}</p>{row.moduleName && <small>{row.moduleName}</small>}<small>{row.source === 'community' ? text.communityRate(row.communityRate ?? null) : `${text.demand} · ${number(row.frequency)}`}</small>{row.warnings.map((warning) => <Notice key={warning}>{warning}</Notice>)}{m.appliedOptions.excluded.includes(row.operatorId) && <button className="v2-text-button" onClick={() => m.exclude(row.operatorId, false)}><RotateCcw size={14} />{text.excluded}</button>}</div></article>)}</div>{rows.length > visible && <button className="v2-button v2-button-secondary" onClick={() => setVisible(visible + 50)}>{text.showMore}</button>}</>
}

function SpecialItems({ data, plan, preference }: Parameters<typeof useSpecialItems>[0]) {
  const m = useSpecialItems({ data, plan, preference })
  return <><p className="v2-muted">{text.specialHint}</p>{!data.specialItems?.length ? <EmptyState title={text.noSpecialItems} /> : <div className="v2-special-items">{data.specialItems.map((item) => <button key={item.id} aria-pressed={m.chosen === item.id} onClick={() => { m.setChosen(item.id); m.setVisible(8) }}><strong>{item.name}</strong><small>{text.itemStock(item.count)}{!item.available && ` · ${text.itemExpired}`}</small></button>)}</div>}{m.selected && <div className="v2-special-detail"><h3>{m.selected.name}</h3><p>{m.selected.scope}</p><p>{text.specialConditions[m.selected.kind]}</p>{m.selected.expiresAt && <p>{text.expiry} {new Date(m.selected.expiresAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}</p>}<a className="v2-text-button" href={m.selected.sourceUrl} target="_blank" rel="noreferrer">{text.itemDetails}</a>{!m.selected.available ? <Notice>{text.itemExpired}</Notice> : !m.recommendations.length ? <EmptyState title={text.noItemUses} /> : <><h3>{text.specialRecommendations}</h3><ol className="v2-special-recommendations">{m.recommendations.slice(0, m.visible).map((row) => <li key={row.key}><strong>{row.name}{row.skill && ` · ${text.skillName(row.skill)} ◆◆◆`}</strong>{row.owned !== undefined && <small>{row.owned ? text.ownedOperator : text.newOperator}</small>}{m.selected!.kind === 'materials' ? <><p>{Object.entries(row.items).map(([id, count]) => `${data.itemNames[id] ?? id} × ${count}`).join(' · ')}</p><small>{row.relief > 0 ? text.materialRelief(row.sanity === null ? text.unpriced : number(row.sanity)) : text.noBatchDemand}</small></> : <><small>{text.demand} {row.demand} · {text.communityRate(row.communityRate)}</small>{m.selected!.kind !== 'selector' && <small>{text.voucherSavings(row.sanity === null ? text.unpriced : number(row.sanity))}</small>}</>}</li>)}</ol>{m.recommendations.length > m.visible && <button className="v2-text-button" onClick={() => m.setVisible(m.visible + 16)}>{text.showMore}</button>}</>}</div>}{data.specialItemsUpdatedAt && <p className="v2-data-date">{text.specialDate} · {new Date(data.specialItemsUpdatedAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}</p>}</>
}
