import { useState } from 'react'
import { ArrowRight, Download, FileJson } from 'lucide-react'
import { copy } from '../../../copy'
import { useDepotValue, formatProfileLabel, formatNumber, formatRankingNote, formatPricingStatus, formatContributionStatus, formatOptionalDate, formatUnitSanityLabel, getUtf8ByteLength } from '../../DepotValuePage'
import AuthForm from '../../../components/AuthForm'
import SklandBindingDialog from '../../../components/SklandBindingDialog'
import SklandIcon from '../../../components/SklandIcon'
import type { V2Session } from '../OptionsDrawer'
import { EmptyState, Facts, Loading, Notice, SectionTitle } from '../components/WorkspaceUI'

const text = copy.tools

export default function Depot({ session }: { session: V2Session }) {
  const m = useDepotValue(session)
  const [source, setSource] = useState(session.user ? 'skland' : 'upload')
  const result = m.result
  return <div className="v2-depot-workspace"><div className="v2-depot-import"><section className="v2-depot-source"><SectionTitle title={text.pages_DepotValuePage_014} description={text.pages_DepotValuePage_015} /><div className="v2-view-switch" role="group" aria-label={copy.v2.toolSource}><button aria-pressed={source === 'skland'} onClick={() => setSource('skland')}><SklandIcon />{text.pages_DepotValuePage_024}</button><button aria-pressed={source === 'upload'} onClick={() => setSource('upload')}><FileJson size={18} />{text.pages_DepotValuePage_016}</button></div>
    <div hidden={source !== 'skland'}>{m.authLoading ? <Loading label={text.pages_DepotValuePage_027} /> : m.authError ? <Notice error>{text.pages_DepotValuePage_080} · {m.authError}<button className="v2-text-button" onClick={session.retryAuth}>{text.pages_DepotValuePage_086}</button></Notice> : !m.auth?.user ? <AuthForm compact allowCdk={false} intro={text.pages_DepotValuePage_028} onAuthenticated={m.handleAuthenticated} submitClassName="v2-button v2-button-primary" /> : <>
      {m.sklandProfiles.length > 0 ? <><label className="v2-field"><span>{copy.v2.account}</span><select className="v2-input" value={m.selectedSklandProfile?.id ?? m.selectedProfileId} onChange={(event) => m.setSelectedProfileId(event.target.value)}>{m.sklandProfiles.map((profile) => <option key={profile.id} value={profile.id}>{formatProfileLabel(profile)}</option>)}</select></label>{m.selectedSklandProfile?.skland_binding?.credential_status === 'invalid' && <Notice error>{text.pages_DepotValuePage_032}</Notice>}<button className="v2-button v2-button-primary" disabled={m.loading !== null || m.profilePreparing} onClick={() => void m.analyzeSkland()}>{m.loading === 'skland' ? text.pages_DepotValuePage_029 : m.selectedSklandProfile?.skland_binding?.credential_status === 'invalid' ? text.pages_DepotValuePage_030 : text.pages_DepotValuePage_031}<ArrowRight size={16} /></button></> : <button className="v2-button v2-button-primary" disabled={m.loading !== null || m.profilePreparing} onClick={() => void m.openSklandBinding()}>{m.profilePreparing ? text.pages_DepotValuePage_033 : text.pages_DepotValuePage_034}</button>}
      <label className="v2-coupon-option"><input type="checkbox" checked={m.sampleConsent} onChange={(event) => m.setSampleConsent(event.target.checked)} /><span>{text.pages_DepotValuePage_087}</span></label>
    </>}<p className="v2-muted">{text.pages_DepotValuePage_035}</p></div>
    <form hidden={source !== 'upload'} onSubmit={m.analyzeUpload} className="v2-depot-upload"><p>{text.pages_DepotValuePage_017}</p><label className="v2-field"><span>{text.pages_DepotValuePage_016}</span><textarea className="v2-input" rows={7} value={m.depotText} placeholder={text.pages_DepotValuePage_019} onChange={(event) => { m.setDepotText(event.target.value); m.setResult(null); m.setError(null) }} /></label><small className="v2-muted">{text.pages_DepotValuePage_085}{m.depotText.trim() && ` · ${text.pages_DepotValuePage_083}${formatNumber(getUtf8ByteLength(m.depotText))}${text.pages_DepotValuePage_084}`}</small><div className="v2-actions"><button className="v2-button v2-button-primary" type="submit" disabled={m.loading !== null || !m.depotText.trim()}>{m.loading === 'upload' ? text.pages_DepotValuePage_022 : text.pages_DepotValuePage_023}</button><button className="v2-text-button" type="button" onClick={() => void m.readClipboard()}>{text.pages_DepotValuePage_018}</button></div></form>
    <Notice error>{m.error}</Notice>
    </section><aside className="v2-depot-explanation"><span className="v2-label">{text.pages_DepotValuePage_036}</span><h2>{text.pages_DepotValuePage_037}</h2><p>{text.pages_DepotValuePage_038}</p><p>{text.pages_DepotValuePage_039}</p><p>{text.pages_DepotValuePage_040}</p></aside></div>
    {result ? <section id="depot-result" className="v2-depot-result"><div className="v2-depot-result-summary"><span className="v2-label">{text.pages_DepotValuePage_041}</span><h2>{text.pages_DepotValuePage_042}<strong>{result.percentile}</strong>{text.pages_DepotValuePage_043}</h2><p>{formatRankingNote(result)}</p><Facts items={[[text.pages_DepotValuePage_044, formatNumber(result.total_equivalent_sanity)], [text.pages_DepotValuePage_045, `${result.priced_count}${text.pages_DepotValuePage_046}`], [text.pages_DepotValuePage_047, `${result.unpriced_count}${text.pages_DepotValuePage_048}`]]} />{result.warnings.map((warning) => <Notice key={warning}>{warning}</Notice>)}
      <SectionTitle title={text.pages_DepotValuePage_049} /><ol className="v2-depot-top-items">{result.top_items.map((item, index) => <li key={item.id}><span className="v2-step-number">{index + 1}</span><div><strong>{item.name}</strong><small>{text.pages_DepotValuePage_050}{formatNumber(item.count)} · {formatUnitSanityLabel(item)}</small></div><b>{formatNumber(item.equivalent_sanity)}</b></li>)}</ol>
      {result.unpriced_items.length > 0 && <details className="v2-disclosure"><summary>{text.pages_DepotValuePage_051}{result.unpriced_count > result.unpriced_items.length ? text.pages_DepotValuePage_098 : ''}</summary><ul>{result.unpriced_items.map((item) => <li key={item.id}>{item.name} × {formatNumber(item.count)}</li>)}</ul></details>}
      <details className="v2-disclosure"><summary>{text.pages_DepotValuePage_090}</summary><Facts items={[[text.pages_DepotValuePage_091, `${formatPricingStatus(result.sources.yituliu)} · ${formatOptionalDate(result.sources.pricing_fetched_at)}`], [text.pages_DepotValuePage_092, result.sources.pricing_snapshot_id?.slice(0, 16) ?? text.pages_DepotValuePage_093], [text.pages_DepotValuePage_094, `${Math.round(result.sources.pricing_coverage * 100)}%`], [text.pages_DepotValuePage_095, result.sources.valuation_version], [text.pages_DepotValuePage_096, formatContributionStatus(result.ranking.contribution_status)], [text.pages_DepotValuePage_097, `${formatOptionalDate(result.generated_at)} · ${result.build_meta.data_version}`]]} /></details>
    </div><aside className="v2-depot-share"><SectionTitle title={text.pages_DepotValuePage_052} description={text.pages_DepotValuePage_053} /><canvas ref={m.canvasRef} width={900} height={1600} aria-label={`${text.pages_DepotValuePage_055}${result.percentile}${text.pages_DepotValuePage_056}`} /><button className="v2-button v2-button-secondary" onClick={m.downloadShareImage}><Download size={16} />{text.pages_DepotValuePage_054}</button></aside></section> : <EmptyState title={text.pages_DepotValuePage_014}>{text.pages_DepotValuePage_015}</EmptyState>}
    <SklandBindingDialog open={m.sklandDialogOpen} profile={m.depotProfile} context="depot" autoStart onOpenChange={m.setSklandDialogOpen} onPayload={m.handleSklandPayload} onCompleted={m.handleSklandCompleted} />
  </div>
}
