import { useState } from 'react'
import { ArrowRight, Package, Search } from 'lucide-react'
import { copy } from '../../../copy'
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '../../../components/ui/dialog'
import SklandBindingDialog from '../../../components/SklandBindingDialog'
import SklandIcon from '../../../components/SklandIcon'
import { itemIconPath } from '../../../lib/inventory-contracts'
import { useInventory, categoryLabel, ledgerEventLabel, fallbackItemIcon } from '../../tool/dashboard/InventorySection'
import { formatShanghaiDateTime } from '../../tool/tool-utils'
import type { V2Session } from '../OptionsDrawer'
import { EmptyState, Facts, Field, Notice } from '../components/WorkspaceUI'
import { V2SectionLoading } from '../V2LoadingScreen'

const text = copy.inventory
type InventoryModel = ReturnType<typeof useInventory>

export default function Inventory({ session, onProfiles }: { session: V2Session; onProfiles: () => void }) {
  const model = useInventory({ onPayload: session.applyAuthPayload, onLifetimeProfileCreated: onProfiles })
  const [view, setView] = useState('items')
  const tasks = model.tasks.filter((task) => task.enabled)
  if (model.loading && !model.inventory) return <V2SectionLoading label={text.loading} />
  return <div className="v2-inventory-workspace">
    <div className="v2-inventory-overview"><Package size={32} aria-hidden="true" /><div><h2>{text.title}</h2><p>{text.description}</p></div><strong>{model.inventory?.stacks.length ?? 0}<small>{copy.v2.inventoryItems}</small></strong></div>
    <Notice error>{model.error}{model.error && <button className="v2-text-button" onClick={() => void model.load()}>{copy.v2.retry}</button>}</Notice>
    <Notice>{model.notice?.message}{model.notice?.action === 'profiles' && <button className="v2-text-button" onClick={onProfiles}>{text.view_profiles}<ArrowRight size={16} /></button>}</Notice>
    <nav className="v2-view-switch" aria-label={text.title}><button aria-pressed={view === 'items'} onClick={() => setView('items')}>{copy.v2.inventoryItems}</button>{tasks.length > 0 && <button aria-pressed={view === 'tasks'} onClick={() => setView('tasks')}>{text.tasks}<span>{tasks.filter((task) => task.status === 'claimable').length}</span></button>}<button aria-pressed={view === 'activity'} onClick={() => setView('activity')}>{copy.v2.inventoryActivity}</button></nav>
    <section hidden={view !== 'items'}>
      <div className="v2-inventory-filters"><div className="v2-filter-group" role="group" aria-label={text.title}>{(['all', 'license_voucher', 'consumable', 'capacity_upgrade', 'gift_pack'] as const).map((category) => <button key={category} aria-pressed={model.category === category} onClick={() => model.setCategory(category)}>{categoryLabel(category)}</button>)}</div><label className="v2-search"><Search size={18} aria-hidden="true" /><input id="inventory-search" aria-label={text.search} placeholder={text.search} value={model.search} onChange={(event) => model.setSearch(event.target.value)} /></label></div>
      {!model.filtered.length ? <EmptyState title={text.empty} /> : <div className="v2-item-shelf">{model.filtered.map((stack) => <button key={stack.stack_id} className="v2-item-tile" onClick={(event) => {
        model.selectedTriggerRef.current = event.currentTarget; model.setSelected(stack); model.setQuantity(1); model.setSelectedRewardCodes([]); model.setProfileId(''); model.setLifetimeDisplayName(''); model.setLifetimeNote('')
      }}><span className="v2-item-art"><img src={itemIconPath(stack.item.icon_key)} onError={fallbackItemIcon} alt="" width={80} height={80} /><b>× {stack.quantity}</b></span><strong>{stack.item.name}</strong><span>{stack.next_expiry_at ? `${text.expires}${formatShanghaiDateTime(stack.next_expiry_at)}` : text.permanent}</span><small>{categoryLabel(stack.item.kind === 'cosmetic' || stack.item.kind === 'badge' ? 'all' : stack.item.kind)}</small></button>)}</div>}
    </section>
    <section hidden={view !== 'tasks'} className="v2-task-list">{tasks.map((task) => <article key={task.code} className="v2-task"><div className="v2-task-status" data-status={task.status}>{task.status === 'claimed' ? '✓' : '○'}</div><div><h2>{task.code === 'bind_skland' && <SklandIcon />}{task.title}</h2><p>{task.description}</p><ul aria-label={text.task_rewards_label(task.title)}>{task.rewards.map((reward) => <li key={reward.item_code}><img src={itemIconPath(reward.icon_key)} onError={fallbackItemIcon} alt="" width={28} height={28} />{reward.name} × {reward.quantity}<small>{reward.expiry.mode === 'never' ? text.permanent : text.expires_after_days(reward.expiry.days)}</small></li>)}</ul></div><button className="v2-button v2-button-secondary" disabled={model.busy || task.status !== 'claimable'} onClick={() => void model.claimTask(task)}>{task.status === 'claimed' ? text.claimed : task.status === 'claimable' ? text.claim : task.status === 'disabled' ? text.disabled : text.incomplete}</button></article>)}</section>
    <section hidden={view !== 'activity'}>{!model.inventory?.recent_events.length ? <EmptyState title={text.empty} /> : <ol className="v2-activity-list">{model.inventory.recent_events.map((event) => <li key={event.id}><time dateTime={event.created_at}>{formatShanghaiDateTime(event.created_at)}</time><img src={itemIconPath(event.icon_key ?? 'placeholder')} onError={fallbackItemIcon} alt="" width={36} height={36} /><div><strong>{event.item_name ?? event.item_code}</strong><p>{ledgerEventLabel(event.event_type)}</p></div><b>× {event.quantity}</b></li>)}</ol>}</section>
    <ItemDetails model={model} />
    <Dialog open={Boolean(model.rewards?.length)} onOpenChange={(open) => { if (!open) model.setRewards(undefined) }}><DialogContent className="v2-item-dialog" onCloseAutoFocus={(event) => { event.preventDefault(); (model.selectedTriggerRef.current?.isConnected ? model.selectedTriggerRef.current : document.getElementById('inventory-search'))?.focus() }}><DialogTitle>{text.rewards_received}</DialogTitle><DialogDescription>{text.rewards_received_help}</DialogDescription><ul className="v2-rewards">{model.rewards?.map((reward) => <li key={`${reward.item_code}:${reward.expires_at}`}><img src={itemIconPath(reward.icon_key)} onError={fallbackItemIcon} alt="" width={64} height={64} /><strong>{reward.name} × {reward.quantity}</strong><span>{reward.expires_at ? formatShanghaiDateTime(reward.expires_at) : text.permanent}</span></li>)}</ul><DialogClose className="v2-button v2-button-primary">{text.close}</DialogClose></DialogContent></Dialog>
    <SklandBindingDialog open={model.lifetimeDialogOpen} profile={null} context="lifetime_voucher_use" onOpenChange={model.setLifetimeDialogOpen} onPayload={model.handleLifetimePayload} />
  </div>
}

function ItemDetails({ model: m }: { model: InventoryModel }) {
  const item = m.selected
  return <Dialog open={Boolean(item)} onOpenChange={(open) => { if (!open && !m.busy) m.setSelected(null) }}><DialogContent className="v2-item-dialog" onCloseAutoFocus={(event) => {
    event.preventDefault()
    if (!m.lifetimeDialogOpen && !m.rewards?.length) (m.selectedTriggerRef.current?.isConnected ? m.selectedTriggerRef.current : document.getElementById('inventory-search'))?.focus()
  }}>
    {item && <><div className="v2-item-dialog-heading"><img src={itemIconPath(item.item.icon_key)} onError={fallbackItemIcon} alt="" width={80} height={80} /><div><span className="v2-label">{categoryLabel(item.item.kind === 'cosmetic' || item.item.kind === 'badge' ? 'all' : item.item.kind)}</span><DialogTitle>{item.item.name}</DialogTitle><DialogDescription>{item.item.description}</DialogDescription></div></div>
      <Notice error>{m.error}</Notice>
      {item.item.kind === 'capacity_upgrade' && <><label className="v2-field"><span>{text.choose_profile}</span><select className="v2-input" disabled={m.busy} value={m.profileId} onChange={(event) => { m.setProfileId(event.target.value); m.setQuantity(1) }}><option value="">{text.choose_profile}</option>{m.inventory?.capacities.map((profile) => <option key={profile.profile_id} value={profile.profile_id}>{profile.display_name}</option>)}</select></label>{m.selectedCapacity && <Facts items={[[text.current, m.selectedCapacity.limit], [text.after_use, Math.min(m.selectedCapacity.maximum, m.selectedCapacity.limit + m.quantity)], [text.maximum, m.selectedCapacity.maximum]]} />}</>}
      {(item.item.kind === 'capacity_upgrade' || item.item.kind === 'gift_pack') && item.quantity > 1 && <Field label={text.use_quantity} help={text.quantity_limit(m.maximumQuantity)} type="number" min={1} max={m.maximumQuantity} step={1} disabled={m.busy || m.maximumQuantity === 0} value={m.quantity} onChange={(event) => m.setQuantity(Number(event.target.value))} />}
      {item.gift_pack && <fieldset ref={m.chestScope} className="v2-gift-options" disabled={m.busy} aria-busy={m.highlightedReward !== null}><legend>{item.gift_pack.opening_rule.mode === 'choice' ? text.chest_choice(item.gift_pack.opening_rule.count, item.gift_pack.opening_rule.allow_duplicates) : item.gift_pack.opening_rule.mode === 'random' ? text.chest_random(item.gift_pack.opening_rule.count, item.gift_pack.opening_rule.allow_duplicates) : text.chest_all}</legend><div>{item.gift_pack.contents.map((reward, index) => <label key={reward.item_code} data-highlighted={m.highlightedReward === index} data-selected={m.selectedRewardCodes.includes(reward.item_code)}>
        <img src={itemIconPath(reward.icon_key)} onError={fallbackItemIcon} alt="" width={48} height={48} /><span><strong>{reward.name} × {reward.quantity}</strong><small>{reward.description}</small><small>{reward.expiry.mode === 'never' ? text.permanent : text.chest_reward_expiry(reward.expiry.days)}</small></span>
        {item.gift_pack!.opening_rule.mode === 'choice' && (item.gift_pack!.opening_rule.allow_duplicates ? <input type="number" className="v2-input" aria-label={text.chest_reward_selection(reward.name)} min={0} max={item.gift_pack!.opening_rule.count - m.selectedRewardCodes.length + m.selectedRewardCodes.filter((code) => code === reward.item_code).length} step={1} value={m.selectedRewardCodes.filter((code) => code === reward.item_code).length} onChange={(event) => {
          const count = Number(event.target.value); const rule = item.gift_pack!.opening_rule
          if (rule.mode !== 'choice' || !Number.isInteger(count) || count < 0 || count > rule.count) return
          m.setSelectedRewardCodes((current) => { const others = current.filter((code) => code !== reward.item_code); return others.length + count <= rule.count ? [...others, ...Array<string>(count).fill(reward.item_code)] : current })
        }} /> : <input type="checkbox" aria-label={reward.name} checked={m.selectedRewardCodes.includes(reward.item_code)} disabled={!m.selectedRewardCodes.includes(reward.item_code) && m.selectedRewardCodes.length >= item.gift_pack!.opening_rule.count} onChange={(event) => { const checked = event.target.checked; m.setSelectedRewardCodes((current) => checked ? [...current, reward.item_code] : current.filter((code) => code !== reward.item_code)) }} />)}
      </label>)}</div>{m.highlightedReward !== null && <p role="status">{text.chest_revealing}</p>}{item.gift_pack.opening_rule.mode === 'choice' && <p role="status">{text.chest_selected(m.selectedRewardCodes.length, item.gift_pack.opening_rule.count)}</p>}</fieldset>}
      {item.actions.includes('context_only') && <Notice>{text.context_only}</Notice>}
      {item.item.code === 'limited_profile_voucher' && <Notice>{text.limited_use_help}</Notice>}
      {item.item.code === 'lifetime_profile_voucher' && <><Notice>{text.lifetime_use_help}</Notice><Field label={text.lifetime_profile_name} maxLength={40} value={m.lifetimeDisplayName} onChange={(event) => m.setLifetimeDisplayName(event.target.value)} placeholder={text.lifetime_profile_name_placeholder} /><label className="v2-field"><span>{text.lifetime_profile_note}</span><textarea className="v2-input" maxLength={500} value={m.lifetimeNote} onChange={(event) => m.setLifetimeNote(event.target.value)} rows={2} placeholder={text.lifetime_profile_note_placeholder} /></label></>}
      <details className="v2-disclosure"><summary>{text.batches}</summary><ul className="v2-batch-list">{item.expiry_buckets.map((bucket, index) => <li key={index}><b>× {bucket.quantity}</b><span>{bucket.expires_at ? formatShanghaiDateTime(bucket.expires_at) : text.permanent}</span></li>)}</ul></details>
      <div className="v2-dialog-actions"><DialogClose disabled={m.busy} className="v2-button v2-button-secondary">{text.close}</DialogClose>{item.item.code === 'lifetime_profile_voucher' ? <><button className="v2-button v2-button-secondary" disabled={m.busy || !m.canUseSelected} onClick={() => void m.createLifetimeProfileWithJson()}>{m.busy ? text.processing : text.create_with_json}</button><button className="v2-button v2-button-primary" disabled={m.busy || !m.canUseSelected} onClick={() => { m.setSelected(null); m.setLifetimeDialogOpen(true) }}><SklandIcon />{text.bind_and_use}</button></> : !item.actions.includes('context_only') && <button className="v2-button v2-button-primary" disabled={m.busy || !m.canUseSelected} onClick={() => void m.runItemAction()}>{m.busy ? text.processing : item.item.kind === 'gift_pack' ? item.gift_pack && item.gift_pack.opening_rule.mode !== 'all' ? text.open_chest : text.open : text.use}</button>}</div>
    </>}
  </DialogContent></Dialog>
}
