import { RefreshCw } from 'lucide-react'
import { copy } from '../../../copy'
import { useServiceStatus, createHistoryCells, historyCellLabel, statusLabel, incidentStatusLabel, incidentImpactLabel, formatUpdatedAt } from '../../StatusPage'
import ServiceStatusBadge from '../../../components/ServiceStatusBadge'
import type { ServiceStatusLevel } from '../../../lib/service-status'
import { EmptyState, Notice, SectionTitle } from '../components/WorkspaceUI'

const text = copy.status

export default function ServiceStatus() {
  const m = useServiceStatus()
  const cells = createHistoryCells(m.currentStatus.history)
  const days = Array.from({ length: 7 }, (_, index) => cells.slice(index * 24, (index + 1) * 24))
  const incidents = [...m.currentStatus.incidents.filter((item) => item.status !== 'resolved'), ...m.currentStatus.incidents.filter((item) => item.status === 'resolved').slice(0, 3)]
  return <div className="v2-service-status"><section className="v2-service-summary"><span className="v2-service-indicator" data-level={m.status?.status ?? 'unknown'} /><div><span className="v2-label">{text.pages_StatusPage_006}</span><h2 aria-live="polite" aria-atomic="true">{m.statusMessage}</h2><p>{m.updatedAt} · {text.pages_StatusPage_007}</p></div><button className="v2-button v2-button-secondary" disabled={m.refreshing} onClick={() => void m.loadStatus()}><RefreshCw size={16} className={m.refreshing ? 'v2-spin' : undefined} />{m.refreshing ? text.pages_StatusPage_070 : text.pages_StatusPage_069}</button></section><Notice error>{m.error && <>{text.pages_StatusPage_021} · {text.pages_StatusPage_022}</>}</Notice>
    <div className="v2-service-components">{[[text.pages_StatusPage_009, text.pages_StatusPage_010, m.optimizationStatus], [text.pages_StatusPage_075, text.pages_StatusPage_076, m.sklandStatus]].map(([title, description, level]) => <article key={title}><div><h3>{title}</h3><p>{description}</p></div>{level ? <ServiceStatusBadge level={level as ServiceStatusLevel} compact /> : <span>{m.error ? text.pages_StatusPage_071 : text.pages_StatusPage_024}</span>}</article>)}</div>
    <section className="v2-service-history"><SectionTitle title={text.pages_StatusPage_037} description={m.currentStatus.history.complete ? `${text.pages_StatusPage_038}${text.pages_StatusPage_039} ${cells.reduce((sum, cell) => sum + cell.sample_count, 0)} ${text.pages_StatusPage_040}` : text.pages_StatusPage_041} /><div className="v2-status-legend">{(['available', 'scaling', 'busy', 'congested', 'overloaded', 'unavailable', 'unknown'] as const).map((level) => <span key={level}><i data-level={level} />{statusLabel(level)}</span>)}</div><div className="v2-service-week" role="grid" aria-label={text.pages_StatusPage_043} aria-rowcount={7} aria-colcount={24}>{days.map((day, index) => <div key={index} role="row"><time>{m.status ? new Date(day[0].bucket_start).toLocaleDateString('zh-CN', { timeZone: 'Asia/Shanghai', month: 'numeric', day: 'numeric' }) : '—'}</time><div>{day.map((cell) => <span key={cell.bucket_start} role="gridcell" data-level={cell.status} title={historyCellLabel(cell)} aria-label={historyCellLabel(cell)} />)}</div></div>)}</div></section>
    <section className="v2-service-incidents"><SectionTitle title={text.pages_StatusPage_045} />{!incidents.length ? <EmptyState title={text.pages_StatusPage_046} /> : incidents.map((incident) => <article key={incident.id} data-state={incident.status}><header><div><h3>{incident.title}</h3><p>{incidentImpactLabel(incident.impact)} · {text.pages_StatusPage_047} {formatUpdatedAt(incident.started_at)}</p></div><span>{incidentStatusLabel(incident.status)}</span></header><ol>{incident.updates.map((update) => <li key={update.id}><time dateTime={update.created_at}>{formatUpdatedAt(update.created_at)}</time><div><strong>{incidentStatusLabel(update.status)}</strong><p>{update.body}</p></div></li>)}</ol></article>)}</section>
    <details className="v2-disclosure"><summary>{text.pages_StatusPage_015}</summary>{([['available', text.pages_StatusPage_016], ['scaling', text.pages_StatusPage_068], ['busy', text.pages_StatusPage_017], ['congested', text.pages_StatusPage_018], ['overloaded', text.pages_StatusPage_064], ['unavailable', text.pages_StatusPage_019]] as const).map(([level, description]) => <div className="v2-status-rule" key={level}><ServiceStatusBadge level={level} compact /><p>{description}</p></div>)}<p>{text.pages_StatusPage_031}</p></details>
  </div>
}
